// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: bouncebot.proto

package protoconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	proto "github.com/srsalisbury/bouncebot/proto"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// BounceBotName is the fully-qualified name of the BounceBot service.
	BounceBotName = "bouncebot.BounceBot"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// BounceBotCreateRoomProcedure is the fully-qualified name of the BounceBot's CreateRoom RPC.
	BounceBotCreateRoomProcedure = "/bouncebot.BounceBot/CreateRoom"
	// BounceBotJoinRoomProcedure is the fully-qualified name of the BounceBot's JoinRoom RPC.
	BounceBotJoinRoomProcedure = "/bouncebot.BounceBot/JoinRoom"
	// BounceBotGetRoomProcedure is the fully-qualified name of the BounceBot's GetRoom RPC.
	BounceBotGetRoomProcedure = "/bouncebot.BounceBot/GetRoom"
	// BounceBotStartGameProcedure is the fully-qualified name of the BounceBot's StartGame RPC.
	BounceBotStartGameProcedure = "/bouncebot.BounceBot/StartGame"
	// BounceBotSubmitSolutionProcedure is the fully-qualified name of the BounceBot's SubmitSolution
	// RPC.
	BounceBotSubmitSolutionProcedure = "/bouncebot.BounceBot/SubmitSolution"
	// BounceBotMarkFinishedSolvingProcedure is the fully-qualified name of the BounceBot's
	// MarkFinishedSolving RPC.
	BounceBotMarkFinishedSolvingProcedure = "/bouncebot.BounceBot/MarkFinishedSolving"
	// BounceBotMarkReadyForNextProcedure is the fully-qualified name of the BounceBot's
	// MarkReadyForNext RPC.
	BounceBotMarkReadyForNextProcedure = "/bouncebot.BounceBot/MarkReadyForNext"
	// BounceBotUpdateRoomSettingsProcedure is the fully-qualified name of the BounceBot's
	// UpdateRoomSettings RPC.
	BounceBotUpdateRoomSettingsProcedure = "/bouncebot.BounceBot/UpdateRoomSettings"
	// BounceBotBootPlayerProcedure is the fully-qualified name of the BounceBot's BootPlayer RPC.
	BounceBotBootPlayerProcedure = "/bouncebot.BounceBot/BootPlayer"
)

// BounceBotClient is a client for the bouncebot.BounceBot service.
type BounceBotClient interface {
	// Room management
	CreateRoom(context.Context, *connect.Request[proto.CreateRoomRequest]) (*connect.Response[proto.CreateRoomResponse], error)
	JoinRoom(context.Context, *connect.Request[proto.JoinRoomRequest]) (*connect.Response[proto.JoinRoomResponse], error)
	GetRoom(context.Context, *connect.Request[proto.GetRoomRequest]) (*connect.Response[proto.Room], error)
	StartGame(context.Context, *connect.Request[proto.StartGameRequest]) (*connect.Response[proto.Room], error)
	SubmitSolution(context.Context, *connect.Request[proto.SubmitSolutionRequest]) (*connect.Response[proto.SubmitSolutionResponse], error)
	MarkFinishedSolving(context.Context, *connect.Request[proto.MarkFinishedSolvingRequest]) (*connect.Response[proto.MarkFinishedSolvingResponse], error)
	MarkReadyForNext(context.Context, *connect.Request[proto.MarkReadyForNextRequest]) (*connect.Response[proto.MarkReadyForNextResponse], error)
	UpdateRoomSettings(context.Context, *connect.Request[proto.UpdateRoomSettingsRequest]) (*connect.Response[proto.UpdateRoomSettingsResponse], error)
	BootPlayer(context.Context, *connect.Request[proto.BootPlayerRequest]) (*connect.Response[proto.BootPlayerResponse], error)
}

// NewBounceBotClient constructs a client for the bouncebot.BounceBot service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBounceBotClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) BounceBotClient {
	baseURL = strings.TrimRight(baseURL, "/")
	bounceBotMethods := proto.File_bouncebot_proto.Services().ByName("BounceBot").Methods()
	return &bounceBotClient{
		createRoom: connect.NewClient[proto.CreateRoomRequest, proto.CreateRoomResponse](
			httpClient,
			baseURL+BounceBotCreateRoomProcedure,
			connect.WithSchema(bounceBotMethods.ByName("CreateRoom")),
			connect.WithClientOptions(opts...),
		),
		joinRoom: connect.NewClient[proto.JoinRoomRequest, proto.JoinRoomResponse](
			httpClient,
			baseURL+BounceBotJoinRoomProcedure,
			connect.WithSchema(bounceBotMethods.ByName("JoinRoom")),
			connect.WithClientOptions(opts...),
		),
		getRoom: connect.NewClient[proto.GetRoomRequest, proto.Room](
			httpClient,
			baseURL+BounceBotGetRoomProcedure,
			connect.WithSchema(bounceBotMethods.ByName("GetRoom")),
			connect.WithClientOptions(opts...),
		),
		startGame: connect.NewClient[proto.StartGameRequest, proto.Room](
			httpClient,
			baseURL+BounceBotStartGameProcedure,
			connect.WithSchema(bounceBotMethods.ByName("StartGame")),
			connect.WithClientOptions(opts...),
		),
		submitSolution: connect.NewClient[proto.SubmitSolutionRequest, proto.SubmitSolutionResponse](
			httpClient,
			baseURL+BounceBotSubmitSolutionProcedure,
			connect.WithSchema(bounceBotMethods.ByName("SubmitSolution")),
			connect.WithClientOptions(opts...),
		),
		markFinishedSolving: connect.NewClient[proto.MarkFinishedSolvingRequest, proto.MarkFinishedSolvingResponse](
			httpClient,
			baseURL+BounceBotMarkFinishedSolvingProcedure,
			connect.WithSchema(bounceBotMethods.ByName("MarkFinishedSolving")),
			connect.WithClientOptions(opts...),
		),
		markReadyForNext: connect.NewClient[proto.MarkReadyForNextRequest, proto.MarkReadyForNextResponse](
			httpClient,
			baseURL+BounceBotMarkReadyForNextProcedure,
			connect.WithSchema(bounceBotMethods.ByName("MarkReadyForNext")),
			connect.WithClientOptions(opts...),
		),
		updateRoomSettings: connect.NewClient[proto.UpdateRoomSettingsRequest, proto.UpdateRoomSettingsResponse](
			httpClient,
			baseURL+BounceBotUpdateRoomSettingsProcedure,
			connect.WithSchema(bounceBotMethods.ByName("UpdateRoomSettings")),
			connect.WithClientOptions(opts...),
		),
		bootPlayer: connect.NewClient[proto.BootPlayerRequest, proto.BootPlayerResponse](
			httpClient,
			baseURL+BounceBotBootPlayerProcedure,
			connect.WithSchema(bounceBotMethods.ByName("BootPlayer")),
			connect.WithClientOptions(opts...),
		),
	}
}

// bounceBotClient implements BounceBotClient.
type bounceBotClient struct {
	createRoom          *connect.Client[proto.CreateRoomRequest, proto.CreateRoomResponse]
	joinRoom            *connect.Client[proto.JoinRoomRequest, proto.JoinRoomResponse]
	getRoom             *connect.Client[proto.GetRoomRequest, proto.Room]
	startGame           *connect.Client[proto.StartGameRequest, proto.Room]
	submitSolution      *connect.Client[proto.SubmitSolutionRequest, proto.SubmitSolutionResponse]
	markFinishedSolving *connect.Client[proto.MarkFinishedSolvingRequest, proto.MarkFinishedSolvingResponse]
	markReadyForNext    *connect.Client[proto.MarkReadyForNextRequest, proto.MarkReadyForNextResponse]
	updateRoomSettings  *connect.Client[proto.UpdateRoomSettingsRequest, proto.UpdateRoomSettingsResponse]
	bootPlayer          *connect.Client[proto.BootPlayerRequest, proto.BootPlayerResponse]
}

// CreateRoom calls bouncebot.BounceBot.CreateRoom.
func (c *bounceBotClient) CreateRoom(ctx context.Context, req *connect.Request[proto.CreateRoomRequest]) (*connect.Response[proto.CreateRoomResponse], error) {
	return c.createRoom.CallUnary(ctx, req)
}

// JoinRoom calls bouncebot.BounceBot.JoinRoom.
func (c *bounceBotClient) JoinRoom(ctx context.Context, req *connect.Request[proto.JoinRoomRequest]) (*connect.Response[proto.JoinRoomResponse], error) {
	return c.joinRoom.CallUnary(ctx, req)
}

// GetRoom calls bouncebot.BounceBot.GetRoom.
func (c *bounceBotClient) GetRoom(ctx context.Context, req *connect.Request[proto.GetRoomRequest]) (*connect.Response[proto.Room], error) {
	return c.getRoom.CallUnary(ctx, req)
}

// StartGame calls bouncebot.BounceBot.StartGame.
func (c *bounceBotClient) StartGame(ctx context.Context, req *connect.Request[proto.StartGameRequest]) (*connect.Response[proto.Room], error) {
	return c.startGame.CallUnary(ctx, req)
}

// SubmitSolution calls bouncebot.BounceBot.SubmitSolution.
func (c *bounceBotClient) SubmitSolution(ctx context.Context, req *connect.Request[proto.SubmitSolutionRequest]) (*connect.Response[proto.SubmitSolutionResponse], error) {
	return c.submitSolution.CallUnary(ctx, req)
}

// MarkFinishedSolving calls bouncebot.BounceBot.MarkFinishedSolving.
func (c *bounceBotClient) MarkFinishedSolving(ctx context.Context, req *connect.Request[proto.MarkFinishedSolvingRequest]) (*connect.Response[proto.MarkFinishedSolvingResponse], error) {
	return c.markFinishedSolving.CallUnary(ctx, req)
}

// MarkReadyForNext calls bouncebot.BounceBot.MarkReadyForNext.
func (c *bounceBotClient) MarkReadyForNext(ctx context.Context, req *connect.Request[proto.MarkReadyForNextRequest]) (*connect.Response[proto.MarkReadyForNextResponse], error) {
	return c.markReadyForNext.CallUnary(ctx, req)
}

// UpdateRoomSettings calls bouncebot.BounceBot.UpdateRoomSettings.
func (c *bounceBotClient) UpdateRoomSettings(ctx context.Context, req *connect.Request[proto.UpdateRoomSettingsRequest]) (*connect.Response[proto.UpdateRoomSettingsResponse], error) {
	return c.updateRoomSettings.CallUnary(ctx, req)
}

// BootPlayer calls bouncebot.BounceBot.BootPlayer.
func (c *bounceBotClient) BootPlayer(ctx context.Context, req *connect.Request[proto.BootPlayerRequest]) (*connect.Response[proto.BootPlayerResponse], error) {
	return c.bootPlayer.CallUnary(ctx, req)
}

// BounceBotHandler is an implementation of the bouncebot.BounceBot service.
type BounceBotHandler interface {
	// Room management
	CreateRoom(context.Context, *connect.Request[proto.CreateRoomRequest]) (*connect.Response[proto.CreateRoomResponse], error)
	JoinRoom(context.Context, *connect.Request[proto.JoinRoomRequest]) (*connect.Response[proto.JoinRoomResponse], error)
	GetRoom(context.Context, *connect.Request[proto.GetRoomRequest]) (*connect.Response[proto.Room], error)
	StartGame(context.Context, *connect.Request[proto.StartGameRequest]) (*connect.Response[proto.Room], error)
	SubmitSolution(context.Context, *connect.Request[proto.SubmitSolutionRequest]) (*connect.Response[proto.SubmitSolutionResponse], error)
	MarkFinishedSolving(context.Context, *connect.Request[proto.MarkFinishedSolvingRequest]) (*connect.Response[proto.MarkFinishedSolvingResponse], error)
	MarkReadyForNext(context.Context, *connect.Request[proto.MarkReadyForNextRequest]) (*connect.Response[proto.MarkReadyForNextResponse], error)
	UpdateRoomSettings(context.Context, *connect.Request[proto.UpdateRoomSettingsRequest]) (*connect.Response[proto.UpdateRoomSettingsResponse], error)
	BootPlayer(context.Context, *connect.Request[proto.BootPlayerRequest]) (*connect.Response[proto.BootPlayerResponse], error)
}

// NewBounceBotHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBounceBotHandler(svc BounceBotHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	bounceBotMethods := proto.File_bouncebot_proto.Services().ByName("BounceBot").Methods()
	bounceBotCreateRoomHandler := connect.NewUnaryHandler(
		BounceBotCreateRoomProcedure,
		svc.CreateRoom,
		connect.WithSchema(bounceBotMethods.ByName("CreateRoom")),
		connect.WithHandlerOptions(opts...),
	)
	bounceBotJoinRoomHandler := connect.NewUnaryHandler(
		BounceBotJoinRoomProcedure,
		svc.JoinRoom,
		connect.WithSchema(bounceBotMethods.ByName("JoinRoom")),
		connect.WithHandlerOptions(opts...),
	)
	bounceBotGetRoomHandler := connect.NewUnaryHandler(
		BounceBotGetRoomProcedure,
		svc.GetRoom,
		connect.WithSchema(bounceBotMethods.ByName("GetRoom")),
		connect.WithHandlerOptions(opts...),
	)
	bounceBotStartGameHandler := connect.NewUnaryHandler(
		BounceBotStartGameProcedure,
		svc.StartGame,
		connect.WithSchema(bounceBotMethods.ByName("StartGame")),
		connect.WithHandlerOptions(opts...),
	)
	bounceBotSubmitSolutionHandler := connect.NewUnaryHandler(
		BounceBotSubmitSolutionProcedure,
		svc.SubmitSolution,
		connect.WithSchema(bounceBotMethods.ByName("SubmitSolution")),
		connect.WithHandlerOptions(opts...),
	)
	bounceBotMarkFinishedSolvingHandler := connect.NewUnaryHandler(
		BounceBotMarkFinishedSolvingProcedure,
		svc.MarkFinishedSolving,
		connect.WithSchema(bounceBotMethods.ByName("MarkFinishedSolving")),
		connect.WithHandlerOptions(opts...),
	)
	bounceBotMarkReadyForNextHandler := connect.NewUnaryHandler(
		BounceBotMarkReadyForNextProcedure,
		svc.MarkReadyForNext,
		connect.WithSchema(bounceBotMethods.ByName("MarkReadyForNext")),
		connect.WithHandlerOptions(opts...),
	)
	bounceBotUpdateRoomSettingsHandler := connect.NewUnaryHandler(
		BounceBotUpdateRoomSettingsProcedure,
		svc.UpdateRoomSettings,
		connect.WithSchema(bounceBotMethods.ByName("UpdateRoomSettings")),
		connect.WithHandlerOptions(opts...),
	)
	bounceBotBootPlayerHandler := connect.NewUnaryHandler(
		BounceBotBootPlayerProcedure,
		svc.BootPlayer,
		connect.WithSchema(bounceBotMethods.ByName("BootPlayer")),
		connect.WithHandlerOptions(opts...),
	)
	return "/bouncebot.BounceBot/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case BounceBotCreateRoomProcedure:
			bounceBotCreateRoomHandler.ServeHTTP(w, r)
		case BounceBotJoinRoomProcedure:
			bounceBotJoinRoomHandler.ServeHTTP(w, r)
		case BounceBotGetRoomProcedure:
			bounceBotGetRoomHandler.ServeHTTP(w, r)
		case BounceBotStartGameProcedure:
			bounceBotStartGameHandler.ServeHTTP(w, r)
		case BounceBotSubmitSolutionProcedure:
			bounceBotSubmitSolutionHandler.ServeHTTP(w, r)
		case BounceBotMarkFinishedSolvingProcedure:
			bounceBotMarkFinishedSolvingHandler.ServeHTTP(w, r)
		case BounceBotMarkReadyForNextProcedure:
			bounceBotMarkReadyForNextHandler.ServeHTTP(w, r)
		case BounceBotUpdateRoomSettingsProcedure:
			bounceBotUpdateRoomSettingsHandler.ServeHTTP(w, r)
		case BounceBotBootPlayerProcedure:
			bounceBotBootPlayerHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedBounceBotHandler returns CodeUnimplemented from all methods.
type UnimplementedBounceBotHandler struct{}

func (UnimplementedBounceBotHandler) CreateRoom(context.Context, *connect.Request[proto.CreateRoomRequest]) (*connect.Response[proto.CreateRoomResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bouncebot.BounceBot.CreateRoom is not implemented"))
}

func (UnimplementedBounceBotHandler) JoinRoom(context.Context, *connect.Request[proto.JoinRoomRequest]) (*connect.Response[proto.JoinRoomResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bouncebot.BounceBot.JoinRoom is not implemented"))
}

func (UnimplementedBounceBotHandler) GetRoom(context.Context, *connect.Request[proto.GetRoomRequest]) (*connect.Response[proto.Room], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bouncebot.BounceBot.GetRoom is not implemented"))
}

func (UnimplementedBounceBotHandler) StartGame(context.Context, *connect.Request[proto.StartGameRequest]) (*connect.Response[proto.Room], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bouncebot.BounceBot.StartGame is not implemented"))
}

func (UnimplementedBounceBotHandler) SubmitSolution(context.Context, *connect.Request[proto.SubmitSolutionRequest]) (*connect.Response[proto.SubmitSolutionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bouncebot.BounceBot.SubmitSolution is not implemented"))
}

func (UnimplementedBounceBotHandler) MarkFinishedSolving(context.Context, *connect.Request[proto.MarkFinishedSolvingRequest]) (*connect.Response[proto.MarkFinishedSolvingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bouncebot.BounceBot.MarkFinishedSolving is not implemented"))
}

func (UnimplementedBounceBotHandler) MarkReadyForNext(context.Context, *connect.Request[proto.MarkReadyForNextRequest]) (*connect.Response[proto.MarkReadyForNextResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bouncebot.BounceBot.MarkReadyForNext is not implemented"))
}

func (UnimplementedBounceBotHandler) UpdateRoomSettings(context.Context, *connect.Request[proto.UpdateRoomSettingsRequest]) (*connect.Response[proto.UpdateRoomSettingsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bouncebot.BounceBot.UpdateRoomSettings is not implemented"))
}

func (UnimplementedBounceBotHandler) BootPlayer(context.Context, *connect.Request[proto.BootPlayerRequest]) (*connect.Response[proto.BootPlayerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bouncebot.BounceBot.BootPlayer is not implemented"))
}
