// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: bouncebot.proto

package protoconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	proto "github.com/srsalisbury/bouncebot/proto"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// BounceBotName is the fully-qualified name of the BounceBot service.
	BounceBotName = "bouncebot.BounceBot"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// BounceBotMakeGameProcedure is the fully-qualified name of the BounceBot's MakeGame RPC.
	BounceBotMakeGameProcedure = "/bouncebot.BounceBot/MakeGame"
	// BounceBotCheckSolutionProcedure is the fully-qualified name of the BounceBot's CheckSolution RPC.
	BounceBotCheckSolutionProcedure = "/bouncebot.BounceBot/CheckSolution"
	// BounceBotCreateSessionProcedure is the fully-qualified name of the BounceBot's CreateSession RPC.
	BounceBotCreateSessionProcedure = "/bouncebot.BounceBot/CreateSession"
	// BounceBotJoinSessionProcedure is the fully-qualified name of the BounceBot's JoinSession RPC.
	BounceBotJoinSessionProcedure = "/bouncebot.BounceBot/JoinSession"
	// BounceBotGetSessionProcedure is the fully-qualified name of the BounceBot's GetSession RPC.
	BounceBotGetSessionProcedure = "/bouncebot.BounceBot/GetSession"
	// BounceBotStartGameProcedure is the fully-qualified name of the BounceBot's StartGame RPC.
	BounceBotStartGameProcedure = "/bouncebot.BounceBot/StartGame"
	// BounceBotSubmitSolutionProcedure is the fully-qualified name of the BounceBot's SubmitSolution
	// RPC.
	BounceBotSubmitSolutionProcedure = "/bouncebot.BounceBot/SubmitSolution"
	// BounceBotRetractSolutionProcedure is the fully-qualified name of the BounceBot's RetractSolution
	// RPC.
	BounceBotRetractSolutionProcedure = "/bouncebot.BounceBot/RetractSolution"
	// BounceBotMarkDoneProcedure is the fully-qualified name of the BounceBot's MarkDone RPC.
	BounceBotMarkDoneProcedure = "/bouncebot.BounceBot/MarkDone"
)

// BounceBotClient is a client for the bouncebot.BounceBot service.
type BounceBotClient interface {
	MakeGame(context.Context, *connect.Request[proto.MakeGameRequest]) (*connect.Response[proto.Game], error)
	CheckSolution(context.Context, *connect.Request[proto.CheckSolutionRequest]) (*connect.Response[proto.CheckSolutionResponse], error)
	// Session management
	CreateSession(context.Context, *connect.Request[proto.CreateSessionRequest]) (*connect.Response[proto.Session], error)
	JoinSession(context.Context, *connect.Request[proto.JoinSessionRequest]) (*connect.Response[proto.Session], error)
	GetSession(context.Context, *connect.Request[proto.GetSessionRequest]) (*connect.Response[proto.Session], error)
	StartGame(context.Context, *connect.Request[proto.StartGameRequest]) (*connect.Response[proto.Session], error)
	SubmitSolution(context.Context, *connect.Request[proto.SubmitSolutionRequest]) (*connect.Response[proto.SubmitSolutionResponse], error)
	RetractSolution(context.Context, *connect.Request[proto.RetractSolutionRequest]) (*connect.Response[proto.RetractSolutionResponse], error)
	MarkDone(context.Context, *connect.Request[proto.MarkDoneRequest]) (*connect.Response[proto.MarkDoneResponse], error)
}

// NewBounceBotClient constructs a client for the bouncebot.BounceBot service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBounceBotClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) BounceBotClient {
	baseURL = strings.TrimRight(baseURL, "/")
	bounceBotMethods := proto.File_bouncebot_proto.Services().ByName("BounceBot").Methods()
	return &bounceBotClient{
		makeGame: connect.NewClient[proto.MakeGameRequest, proto.Game](
			httpClient,
			baseURL+BounceBotMakeGameProcedure,
			connect.WithSchema(bounceBotMethods.ByName("MakeGame")),
			connect.WithClientOptions(opts...),
		),
		checkSolution: connect.NewClient[proto.CheckSolutionRequest, proto.CheckSolutionResponse](
			httpClient,
			baseURL+BounceBotCheckSolutionProcedure,
			connect.WithSchema(bounceBotMethods.ByName("CheckSolution")),
			connect.WithClientOptions(opts...),
		),
		createSession: connect.NewClient[proto.CreateSessionRequest, proto.Session](
			httpClient,
			baseURL+BounceBotCreateSessionProcedure,
			connect.WithSchema(bounceBotMethods.ByName("CreateSession")),
			connect.WithClientOptions(opts...),
		),
		joinSession: connect.NewClient[proto.JoinSessionRequest, proto.Session](
			httpClient,
			baseURL+BounceBotJoinSessionProcedure,
			connect.WithSchema(bounceBotMethods.ByName("JoinSession")),
			connect.WithClientOptions(opts...),
		),
		getSession: connect.NewClient[proto.GetSessionRequest, proto.Session](
			httpClient,
			baseURL+BounceBotGetSessionProcedure,
			connect.WithSchema(bounceBotMethods.ByName("GetSession")),
			connect.WithClientOptions(opts...),
		),
		startGame: connect.NewClient[proto.StartGameRequest, proto.Session](
			httpClient,
			baseURL+BounceBotStartGameProcedure,
			connect.WithSchema(bounceBotMethods.ByName("StartGame")),
			connect.WithClientOptions(opts...),
		),
		submitSolution: connect.NewClient[proto.SubmitSolutionRequest, proto.SubmitSolutionResponse](
			httpClient,
			baseURL+BounceBotSubmitSolutionProcedure,
			connect.WithSchema(bounceBotMethods.ByName("SubmitSolution")),
			connect.WithClientOptions(opts...),
		),
		retractSolution: connect.NewClient[proto.RetractSolutionRequest, proto.RetractSolutionResponse](
			httpClient,
			baseURL+BounceBotRetractSolutionProcedure,
			connect.WithSchema(bounceBotMethods.ByName("RetractSolution")),
			connect.WithClientOptions(opts...),
		),
		markDone: connect.NewClient[proto.MarkDoneRequest, proto.MarkDoneResponse](
			httpClient,
			baseURL+BounceBotMarkDoneProcedure,
			connect.WithSchema(bounceBotMethods.ByName("MarkDone")),
			connect.WithClientOptions(opts...),
		),
	}
}

// bounceBotClient implements BounceBotClient.
type bounceBotClient struct {
	makeGame        *connect.Client[proto.MakeGameRequest, proto.Game]
	checkSolution   *connect.Client[proto.CheckSolutionRequest, proto.CheckSolutionResponse]
	createSession   *connect.Client[proto.CreateSessionRequest, proto.Session]
	joinSession     *connect.Client[proto.JoinSessionRequest, proto.Session]
	getSession      *connect.Client[proto.GetSessionRequest, proto.Session]
	startGame       *connect.Client[proto.StartGameRequest, proto.Session]
	submitSolution  *connect.Client[proto.SubmitSolutionRequest, proto.SubmitSolutionResponse]
	retractSolution *connect.Client[proto.RetractSolutionRequest, proto.RetractSolutionResponse]
	markDone        *connect.Client[proto.MarkDoneRequest, proto.MarkDoneResponse]
}

// MakeGame calls bouncebot.BounceBot.MakeGame.
func (c *bounceBotClient) MakeGame(ctx context.Context, req *connect.Request[proto.MakeGameRequest]) (*connect.Response[proto.Game], error) {
	return c.makeGame.CallUnary(ctx, req)
}

// CheckSolution calls bouncebot.BounceBot.CheckSolution.
func (c *bounceBotClient) CheckSolution(ctx context.Context, req *connect.Request[proto.CheckSolutionRequest]) (*connect.Response[proto.CheckSolutionResponse], error) {
	return c.checkSolution.CallUnary(ctx, req)
}

// CreateSession calls bouncebot.BounceBot.CreateSession.
func (c *bounceBotClient) CreateSession(ctx context.Context, req *connect.Request[proto.CreateSessionRequest]) (*connect.Response[proto.Session], error) {
	return c.createSession.CallUnary(ctx, req)
}

// JoinSession calls bouncebot.BounceBot.JoinSession.
func (c *bounceBotClient) JoinSession(ctx context.Context, req *connect.Request[proto.JoinSessionRequest]) (*connect.Response[proto.Session], error) {
	return c.joinSession.CallUnary(ctx, req)
}

// GetSession calls bouncebot.BounceBot.GetSession.
func (c *bounceBotClient) GetSession(ctx context.Context, req *connect.Request[proto.GetSessionRequest]) (*connect.Response[proto.Session], error) {
	return c.getSession.CallUnary(ctx, req)
}

// StartGame calls bouncebot.BounceBot.StartGame.
func (c *bounceBotClient) StartGame(ctx context.Context, req *connect.Request[proto.StartGameRequest]) (*connect.Response[proto.Session], error) {
	return c.startGame.CallUnary(ctx, req)
}

// SubmitSolution calls bouncebot.BounceBot.SubmitSolution.
func (c *bounceBotClient) SubmitSolution(ctx context.Context, req *connect.Request[proto.SubmitSolutionRequest]) (*connect.Response[proto.SubmitSolutionResponse], error) {
	return c.submitSolution.CallUnary(ctx, req)
}

// RetractSolution calls bouncebot.BounceBot.RetractSolution.
func (c *bounceBotClient) RetractSolution(ctx context.Context, req *connect.Request[proto.RetractSolutionRequest]) (*connect.Response[proto.RetractSolutionResponse], error) {
	return c.retractSolution.CallUnary(ctx, req)
}

// MarkDone calls bouncebot.BounceBot.MarkDone.
func (c *bounceBotClient) MarkDone(ctx context.Context, req *connect.Request[proto.MarkDoneRequest]) (*connect.Response[proto.MarkDoneResponse], error) {
	return c.markDone.CallUnary(ctx, req)
}

// BounceBotHandler is an implementation of the bouncebot.BounceBot service.
type BounceBotHandler interface {
	MakeGame(context.Context, *connect.Request[proto.MakeGameRequest]) (*connect.Response[proto.Game], error)
	CheckSolution(context.Context, *connect.Request[proto.CheckSolutionRequest]) (*connect.Response[proto.CheckSolutionResponse], error)
	// Session management
	CreateSession(context.Context, *connect.Request[proto.CreateSessionRequest]) (*connect.Response[proto.Session], error)
	JoinSession(context.Context, *connect.Request[proto.JoinSessionRequest]) (*connect.Response[proto.Session], error)
	GetSession(context.Context, *connect.Request[proto.GetSessionRequest]) (*connect.Response[proto.Session], error)
	StartGame(context.Context, *connect.Request[proto.StartGameRequest]) (*connect.Response[proto.Session], error)
	SubmitSolution(context.Context, *connect.Request[proto.SubmitSolutionRequest]) (*connect.Response[proto.SubmitSolutionResponse], error)
	RetractSolution(context.Context, *connect.Request[proto.RetractSolutionRequest]) (*connect.Response[proto.RetractSolutionResponse], error)
	MarkDone(context.Context, *connect.Request[proto.MarkDoneRequest]) (*connect.Response[proto.MarkDoneResponse], error)
}

// NewBounceBotHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBounceBotHandler(svc BounceBotHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	bounceBotMethods := proto.File_bouncebot_proto.Services().ByName("BounceBot").Methods()
	bounceBotMakeGameHandler := connect.NewUnaryHandler(
		BounceBotMakeGameProcedure,
		svc.MakeGame,
		connect.WithSchema(bounceBotMethods.ByName("MakeGame")),
		connect.WithHandlerOptions(opts...),
	)
	bounceBotCheckSolutionHandler := connect.NewUnaryHandler(
		BounceBotCheckSolutionProcedure,
		svc.CheckSolution,
		connect.WithSchema(bounceBotMethods.ByName("CheckSolution")),
		connect.WithHandlerOptions(opts...),
	)
	bounceBotCreateSessionHandler := connect.NewUnaryHandler(
		BounceBotCreateSessionProcedure,
		svc.CreateSession,
		connect.WithSchema(bounceBotMethods.ByName("CreateSession")),
		connect.WithHandlerOptions(opts...),
	)
	bounceBotJoinSessionHandler := connect.NewUnaryHandler(
		BounceBotJoinSessionProcedure,
		svc.JoinSession,
		connect.WithSchema(bounceBotMethods.ByName("JoinSession")),
		connect.WithHandlerOptions(opts...),
	)
	bounceBotGetSessionHandler := connect.NewUnaryHandler(
		BounceBotGetSessionProcedure,
		svc.GetSession,
		connect.WithSchema(bounceBotMethods.ByName("GetSession")),
		connect.WithHandlerOptions(opts...),
	)
	bounceBotStartGameHandler := connect.NewUnaryHandler(
		BounceBotStartGameProcedure,
		svc.StartGame,
		connect.WithSchema(bounceBotMethods.ByName("StartGame")),
		connect.WithHandlerOptions(opts...),
	)
	bounceBotSubmitSolutionHandler := connect.NewUnaryHandler(
		BounceBotSubmitSolutionProcedure,
		svc.SubmitSolution,
		connect.WithSchema(bounceBotMethods.ByName("SubmitSolution")),
		connect.WithHandlerOptions(opts...),
	)
	bounceBotRetractSolutionHandler := connect.NewUnaryHandler(
		BounceBotRetractSolutionProcedure,
		svc.RetractSolution,
		connect.WithSchema(bounceBotMethods.ByName("RetractSolution")),
		connect.WithHandlerOptions(opts...),
	)
	bounceBotMarkDoneHandler := connect.NewUnaryHandler(
		BounceBotMarkDoneProcedure,
		svc.MarkDone,
		connect.WithSchema(bounceBotMethods.ByName("MarkDone")),
		connect.WithHandlerOptions(opts...),
	)
	return "/bouncebot.BounceBot/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case BounceBotMakeGameProcedure:
			bounceBotMakeGameHandler.ServeHTTP(w, r)
		case BounceBotCheckSolutionProcedure:
			bounceBotCheckSolutionHandler.ServeHTTP(w, r)
		case BounceBotCreateSessionProcedure:
			bounceBotCreateSessionHandler.ServeHTTP(w, r)
		case BounceBotJoinSessionProcedure:
			bounceBotJoinSessionHandler.ServeHTTP(w, r)
		case BounceBotGetSessionProcedure:
			bounceBotGetSessionHandler.ServeHTTP(w, r)
		case BounceBotStartGameProcedure:
			bounceBotStartGameHandler.ServeHTTP(w, r)
		case BounceBotSubmitSolutionProcedure:
			bounceBotSubmitSolutionHandler.ServeHTTP(w, r)
		case BounceBotRetractSolutionProcedure:
			bounceBotRetractSolutionHandler.ServeHTTP(w, r)
		case BounceBotMarkDoneProcedure:
			bounceBotMarkDoneHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedBounceBotHandler returns CodeUnimplemented from all methods.
type UnimplementedBounceBotHandler struct{}

func (UnimplementedBounceBotHandler) MakeGame(context.Context, *connect.Request[proto.MakeGameRequest]) (*connect.Response[proto.Game], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bouncebot.BounceBot.MakeGame is not implemented"))
}

func (UnimplementedBounceBotHandler) CheckSolution(context.Context, *connect.Request[proto.CheckSolutionRequest]) (*connect.Response[proto.CheckSolutionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bouncebot.BounceBot.CheckSolution is not implemented"))
}

func (UnimplementedBounceBotHandler) CreateSession(context.Context, *connect.Request[proto.CreateSessionRequest]) (*connect.Response[proto.Session], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bouncebot.BounceBot.CreateSession is not implemented"))
}

func (UnimplementedBounceBotHandler) JoinSession(context.Context, *connect.Request[proto.JoinSessionRequest]) (*connect.Response[proto.Session], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bouncebot.BounceBot.JoinSession is not implemented"))
}

func (UnimplementedBounceBotHandler) GetSession(context.Context, *connect.Request[proto.GetSessionRequest]) (*connect.Response[proto.Session], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bouncebot.BounceBot.GetSession is not implemented"))
}

func (UnimplementedBounceBotHandler) StartGame(context.Context, *connect.Request[proto.StartGameRequest]) (*connect.Response[proto.Session], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bouncebot.BounceBot.StartGame is not implemented"))
}

func (UnimplementedBounceBotHandler) SubmitSolution(context.Context, *connect.Request[proto.SubmitSolutionRequest]) (*connect.Response[proto.SubmitSolutionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bouncebot.BounceBot.SubmitSolution is not implemented"))
}

func (UnimplementedBounceBotHandler) RetractSolution(context.Context, *connect.Request[proto.RetractSolutionRequest]) (*connect.Response[proto.RetractSolutionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bouncebot.BounceBot.RetractSolution is not implemented"))
}

func (UnimplementedBounceBotHandler) MarkDone(context.Context, *connect.Request[proto.MarkDoneRequest]) (*connect.Response[proto.MarkDoneResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bouncebot.BounceBot.MarkDone is not implemented"))
}
