// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: bouncebot.proto

package protoconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	proto "github.com/srsalisbury/bouncebot/proto"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// BounceBotName is the fully-qualified name of the BounceBot service.
	BounceBotName = "bouncebot.BounceBot"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// BounceBotMakeGameProcedure is the fully-qualified name of the BounceBot's MakeGame RPC.
	BounceBotMakeGameProcedure = "/bouncebot.BounceBot/MakeGame"
	// BounceBotCheckSolutionProcedure is the fully-qualified name of the BounceBot's CheckSolution RPC.
	BounceBotCheckSolutionProcedure = "/bouncebot.BounceBot/CheckSolution"
)

// BounceBotClient is a client for the bouncebot.BounceBot service.
type BounceBotClient interface {
	MakeGame(context.Context, *connect.Request[proto.MakeGameRequest]) (*connect.Response[proto.Game], error)
	CheckSolution(context.Context, *connect.Request[proto.CheckSolutionRequest]) (*connect.Response[proto.CheckSolutionResponse], error)
}

// NewBounceBotClient constructs a client for the bouncebot.BounceBot service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBounceBotClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) BounceBotClient {
	baseURL = strings.TrimRight(baseURL, "/")
	bounceBotMethods := proto.File_bouncebot_proto.Services().ByName("BounceBot").Methods()
	return &bounceBotClient{
		makeGame: connect.NewClient[proto.MakeGameRequest, proto.Game](
			httpClient,
			baseURL+BounceBotMakeGameProcedure,
			connect.WithSchema(bounceBotMethods.ByName("MakeGame")),
			connect.WithClientOptions(opts...),
		),
		checkSolution: connect.NewClient[proto.CheckSolutionRequest, proto.CheckSolutionResponse](
			httpClient,
			baseURL+BounceBotCheckSolutionProcedure,
			connect.WithSchema(bounceBotMethods.ByName("CheckSolution")),
			connect.WithClientOptions(opts...),
		),
	}
}

// bounceBotClient implements BounceBotClient.
type bounceBotClient struct {
	makeGame      *connect.Client[proto.MakeGameRequest, proto.Game]
	checkSolution *connect.Client[proto.CheckSolutionRequest, proto.CheckSolutionResponse]
}

// MakeGame calls bouncebot.BounceBot.MakeGame.
func (c *bounceBotClient) MakeGame(ctx context.Context, req *connect.Request[proto.MakeGameRequest]) (*connect.Response[proto.Game], error) {
	return c.makeGame.CallUnary(ctx, req)
}

// CheckSolution calls bouncebot.BounceBot.CheckSolution.
func (c *bounceBotClient) CheckSolution(ctx context.Context, req *connect.Request[proto.CheckSolutionRequest]) (*connect.Response[proto.CheckSolutionResponse], error) {
	return c.checkSolution.CallUnary(ctx, req)
}

// BounceBotHandler is an implementation of the bouncebot.BounceBot service.
type BounceBotHandler interface {
	MakeGame(context.Context, *connect.Request[proto.MakeGameRequest]) (*connect.Response[proto.Game], error)
	CheckSolution(context.Context, *connect.Request[proto.CheckSolutionRequest]) (*connect.Response[proto.CheckSolutionResponse], error)
}

// NewBounceBotHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBounceBotHandler(svc BounceBotHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	bounceBotMethods := proto.File_bouncebot_proto.Services().ByName("BounceBot").Methods()
	bounceBotMakeGameHandler := connect.NewUnaryHandler(
		BounceBotMakeGameProcedure,
		svc.MakeGame,
		connect.WithSchema(bounceBotMethods.ByName("MakeGame")),
		connect.WithHandlerOptions(opts...),
	)
	bounceBotCheckSolutionHandler := connect.NewUnaryHandler(
		BounceBotCheckSolutionProcedure,
		svc.CheckSolution,
		connect.WithSchema(bounceBotMethods.ByName("CheckSolution")),
		connect.WithHandlerOptions(opts...),
	)
	return "/bouncebot.BounceBot/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case BounceBotMakeGameProcedure:
			bounceBotMakeGameHandler.ServeHTTP(w, r)
		case BounceBotCheckSolutionProcedure:
			bounceBotCheckSolutionHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedBounceBotHandler returns CodeUnimplemented from all methods.
type UnimplementedBounceBotHandler struct{}

func (UnimplementedBounceBotHandler) MakeGame(context.Context, *connect.Request[proto.MakeGameRequest]) (*connect.Response[proto.Game], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bouncebot.BounceBot.MakeGame is not implemented"))
}

func (UnimplementedBounceBotHandler) CheckSolution(context.Context, *connect.Request[proto.CheckSolutionRequest]) (*connect.Response[proto.CheckSolutionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("bouncebot.BounceBot.CheckSolution is not implemented"))
}
