// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: bouncebot.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BounceBot_MakeGame_FullMethodName            = "/bouncebot.BounceBot/MakeGame"
	BounceBot_CheckSolution_FullMethodName       = "/bouncebot.BounceBot/CheckSolution"
	BounceBot_CreateSession_FullMethodName       = "/bouncebot.BounceBot/CreateSession"
	BounceBot_JoinSession_FullMethodName         = "/bouncebot.BounceBot/JoinSession"
	BounceBot_GetSession_FullMethodName          = "/bouncebot.BounceBot/GetSession"
	BounceBot_StartGame_FullMethodName           = "/bouncebot.BounceBot/StartGame"
	BounceBot_SubmitSolution_FullMethodName      = "/bouncebot.BounceBot/SubmitSolution"
	BounceBot_RetractSolution_FullMethodName     = "/bouncebot.BounceBot/RetractSolution"
	BounceBot_MarkFinishedSolving_FullMethodName = "/bouncebot.BounceBot/MarkFinishedSolving"
	BounceBot_MarkReadyForNext_FullMethodName    = "/bouncebot.BounceBot/MarkReadyForNext"
)

// BounceBotClient is the client API for BounceBot service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for client to fetch a game board and return results.
type BounceBotClient interface {
	MakeGame(ctx context.Context, in *MakeGameRequest, opts ...grpc.CallOption) (*Game, error)
	CheckSolution(ctx context.Context, in *CheckSolutionRequest, opts ...grpc.CallOption) (*CheckSolutionResponse, error)
	// Session management
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*Session, error)
	JoinSession(ctx context.Context, in *JoinSessionRequest, opts ...grpc.CallOption) (*Session, error)
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*Session, error)
	StartGame(ctx context.Context, in *StartGameRequest, opts ...grpc.CallOption) (*Session, error)
	SubmitSolution(ctx context.Context, in *SubmitSolutionRequest, opts ...grpc.CallOption) (*SubmitSolutionResponse, error)
	RetractSolution(ctx context.Context, in *RetractSolutionRequest, opts ...grpc.CallOption) (*RetractSolutionResponse, error)
	MarkFinishedSolving(ctx context.Context, in *MarkFinishedSolvingRequest, opts ...grpc.CallOption) (*MarkFinishedSolvingResponse, error)
	MarkReadyForNext(ctx context.Context, in *MarkReadyForNextRequest, opts ...grpc.CallOption) (*MarkReadyForNextResponse, error)
}

type bounceBotClient struct {
	cc grpc.ClientConnInterface
}

func NewBounceBotClient(cc grpc.ClientConnInterface) BounceBotClient {
	return &bounceBotClient{cc}
}

func (c *bounceBotClient) MakeGame(ctx context.Context, in *MakeGameRequest, opts ...grpc.CallOption) (*Game, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Game)
	err := c.cc.Invoke(ctx, BounceBot_MakeGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bounceBotClient) CheckSolution(ctx context.Context, in *CheckSolutionRequest, opts ...grpc.CallOption) (*CheckSolutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckSolutionResponse)
	err := c.cc.Invoke(ctx, BounceBot_CheckSolution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bounceBotClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, BounceBot_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bounceBotClient) JoinSession(ctx context.Context, in *JoinSessionRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, BounceBot_JoinSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bounceBotClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, BounceBot_GetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bounceBotClient) StartGame(ctx context.Context, in *StartGameRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, BounceBot_StartGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bounceBotClient) SubmitSolution(ctx context.Context, in *SubmitSolutionRequest, opts ...grpc.CallOption) (*SubmitSolutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitSolutionResponse)
	err := c.cc.Invoke(ctx, BounceBot_SubmitSolution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bounceBotClient) RetractSolution(ctx context.Context, in *RetractSolutionRequest, opts ...grpc.CallOption) (*RetractSolutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetractSolutionResponse)
	err := c.cc.Invoke(ctx, BounceBot_RetractSolution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bounceBotClient) MarkFinishedSolving(ctx context.Context, in *MarkFinishedSolvingRequest, opts ...grpc.CallOption) (*MarkFinishedSolvingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkFinishedSolvingResponse)
	err := c.cc.Invoke(ctx, BounceBot_MarkFinishedSolving_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bounceBotClient) MarkReadyForNext(ctx context.Context, in *MarkReadyForNextRequest, opts ...grpc.CallOption) (*MarkReadyForNextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkReadyForNextResponse)
	err := c.cc.Invoke(ctx, BounceBot_MarkReadyForNext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BounceBotServer is the server API for BounceBot service.
// All implementations must embed UnimplementedBounceBotServer
// for forward compatibility.
//
// Service for client to fetch a game board and return results.
type BounceBotServer interface {
	MakeGame(context.Context, *MakeGameRequest) (*Game, error)
	CheckSolution(context.Context, *CheckSolutionRequest) (*CheckSolutionResponse, error)
	// Session management
	CreateSession(context.Context, *CreateSessionRequest) (*Session, error)
	JoinSession(context.Context, *JoinSessionRequest) (*Session, error)
	GetSession(context.Context, *GetSessionRequest) (*Session, error)
	StartGame(context.Context, *StartGameRequest) (*Session, error)
	SubmitSolution(context.Context, *SubmitSolutionRequest) (*SubmitSolutionResponse, error)
	RetractSolution(context.Context, *RetractSolutionRequest) (*RetractSolutionResponse, error)
	MarkFinishedSolving(context.Context, *MarkFinishedSolvingRequest) (*MarkFinishedSolvingResponse, error)
	MarkReadyForNext(context.Context, *MarkReadyForNextRequest) (*MarkReadyForNextResponse, error)
	mustEmbedUnimplementedBounceBotServer()
}

// UnimplementedBounceBotServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBounceBotServer struct{}

func (UnimplementedBounceBotServer) MakeGame(context.Context, *MakeGameRequest) (*Game, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MakeGame not implemented")
}
func (UnimplementedBounceBotServer) CheckSolution(context.Context, *CheckSolutionRequest) (*CheckSolutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckSolution not implemented")
}
func (UnimplementedBounceBotServer) CreateSession(context.Context, *CreateSessionRequest) (*Session, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedBounceBotServer) JoinSession(context.Context, *JoinSessionRequest) (*Session, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinSession not implemented")
}
func (UnimplementedBounceBotServer) GetSession(context.Context, *GetSessionRequest) (*Session, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedBounceBotServer) StartGame(context.Context, *StartGameRequest) (*Session, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartGame not implemented")
}
func (UnimplementedBounceBotServer) SubmitSolution(context.Context, *SubmitSolutionRequest) (*SubmitSolutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitSolution not implemented")
}
func (UnimplementedBounceBotServer) RetractSolution(context.Context, *RetractSolutionRequest) (*RetractSolutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetractSolution not implemented")
}
func (UnimplementedBounceBotServer) MarkFinishedSolving(context.Context, *MarkFinishedSolvingRequest) (*MarkFinishedSolvingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkFinishedSolving not implemented")
}
func (UnimplementedBounceBotServer) MarkReadyForNext(context.Context, *MarkReadyForNextRequest) (*MarkReadyForNextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkReadyForNext not implemented")
}
func (UnimplementedBounceBotServer) mustEmbedUnimplementedBounceBotServer() {}
func (UnimplementedBounceBotServer) testEmbeddedByValue()                   {}

// UnsafeBounceBotServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BounceBotServer will
// result in compilation errors.
type UnsafeBounceBotServer interface {
	mustEmbedUnimplementedBounceBotServer()
}

func RegisterBounceBotServer(s grpc.ServiceRegistrar, srv BounceBotServer) {
	// If the following call pancis, it indicates UnimplementedBounceBotServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BounceBot_ServiceDesc, srv)
}

func _BounceBot_MakeGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MakeGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BounceBotServer).MakeGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BounceBot_MakeGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BounceBotServer).MakeGame(ctx, req.(*MakeGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BounceBot_CheckSolution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckSolutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BounceBotServer).CheckSolution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BounceBot_CheckSolution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BounceBotServer).CheckSolution(ctx, req.(*CheckSolutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BounceBot_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BounceBotServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BounceBot_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BounceBotServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BounceBot_JoinSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BounceBotServer).JoinSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BounceBot_JoinSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BounceBotServer).JoinSession(ctx, req.(*JoinSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BounceBot_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BounceBotServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BounceBot_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BounceBotServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BounceBot_StartGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BounceBotServer).StartGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BounceBot_StartGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BounceBotServer).StartGame(ctx, req.(*StartGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BounceBot_SubmitSolution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitSolutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BounceBotServer).SubmitSolution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BounceBot_SubmitSolution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BounceBotServer).SubmitSolution(ctx, req.(*SubmitSolutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BounceBot_RetractSolution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetractSolutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BounceBotServer).RetractSolution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BounceBot_RetractSolution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BounceBotServer).RetractSolution(ctx, req.(*RetractSolutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BounceBot_MarkFinishedSolving_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkFinishedSolvingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BounceBotServer).MarkFinishedSolving(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BounceBot_MarkFinishedSolving_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BounceBotServer).MarkFinishedSolving(ctx, req.(*MarkFinishedSolvingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BounceBot_MarkReadyForNext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkReadyForNextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BounceBotServer).MarkReadyForNext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BounceBot_MarkReadyForNext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BounceBotServer).MarkReadyForNext(ctx, req.(*MarkReadyForNextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BounceBot_ServiceDesc is the grpc.ServiceDesc for BounceBot service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BounceBot_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bouncebot.BounceBot",
	HandlerType: (*BounceBotServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MakeGame",
			Handler:    _BounceBot_MakeGame_Handler,
		},
		{
			MethodName: "CheckSolution",
			Handler:    _BounceBot_CheckSolution_Handler,
		},
		{
			MethodName: "CreateSession",
			Handler:    _BounceBot_CreateSession_Handler,
		},
		{
			MethodName: "JoinSession",
			Handler:    _BounceBot_JoinSession_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _BounceBot_GetSession_Handler,
		},
		{
			MethodName: "StartGame",
			Handler:    _BounceBot_StartGame_Handler,
		},
		{
			MethodName: "SubmitSolution",
			Handler:    _BounceBot_SubmitSolution_Handler,
		},
		{
			MethodName: "RetractSolution",
			Handler:    _BounceBot_RetractSolution_Handler,
		},
		{
			MethodName: "MarkFinishedSolving",
			Handler:    _BounceBot_MarkFinishedSolving_Handler,
		},
		{
			MethodName: "MarkReadyForNext",
			Handler:    _BounceBot_MarkReadyForNext_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bouncebot.proto",
}
