// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: bouncebot.proto

package bouncebot

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BounceBot_GetBoard_FullMethodName = "/bouncebot.BounceBot/GetBoard"
)

// BounceBotClient is the client API for BounceBot service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for client to fetch a game board and return results.
type BounceBotClient interface {
	GetBoard(ctx context.Context, in *GetBoardRequest, opts ...grpc.CallOption) (*GetBoardResponse, error)
}

type bounceBotClient struct {
	cc grpc.ClientConnInterface
}

func NewBounceBotClient(cc grpc.ClientConnInterface) BounceBotClient {
	return &bounceBotClient{cc}
}

func (c *bounceBotClient) GetBoard(ctx context.Context, in *GetBoardRequest, opts ...grpc.CallOption) (*GetBoardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBoardResponse)
	err := c.cc.Invoke(ctx, BounceBot_GetBoard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BounceBotServer is the server API for BounceBot service.
// All implementations must embed UnimplementedBounceBotServer
// for forward compatibility.
//
// Service for client to fetch a game board and return results.
type BounceBotServer interface {
	GetBoard(context.Context, *GetBoardRequest) (*GetBoardResponse, error)
	mustEmbedUnimplementedBounceBotServer()
}

// UnimplementedBounceBotServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBounceBotServer struct{}

func (UnimplementedBounceBotServer) GetBoard(context.Context, *GetBoardRequest) (*GetBoardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBoard not implemented")
}
func (UnimplementedBounceBotServer) mustEmbedUnimplementedBounceBotServer() {}
func (UnimplementedBounceBotServer) testEmbeddedByValue()                   {}

// UnsafeBounceBotServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BounceBotServer will
// result in compilation errors.
type UnsafeBounceBotServer interface {
	mustEmbedUnimplementedBounceBotServer()
}

func RegisterBounceBotServer(s grpc.ServiceRegistrar, srv BounceBotServer) {
	// If the following call pancis, it indicates UnimplementedBounceBotServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BounceBot_ServiceDesc, srv)
}

func _BounceBot_GetBoard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBoardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BounceBotServer).GetBoard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BounceBot_GetBoard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BounceBotServer).GetBoard(ctx, req.(*GetBoardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BounceBot_ServiceDesc is the grpc.ServiceDesc for BounceBot service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BounceBot_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bouncebot.BounceBot",
	HandlerType: (*BounceBotServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBoard",
			Handler:    _BounceBot_GetBoard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bouncebot.proto",
}
