// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: bouncebot.proto

package bouncebot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Board grid position.
// This refers to a board position relative to the upper-left board cell.
// For robots, this is the cell the robot sits on.
// For vertical walls, this is the cell to the left of the wall (the wall is to the right).
// For horizontal walls, this is the cell above the wall (the wall below the cell).
type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_bouncebot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_bouncebot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_bouncebot_proto_rawDescGZIP(), []int{0}
}

func (x *Position) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Board struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Board is square with size cells horizontally and vertically.
	Size int32 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	// Locations of the vertical walls (edges of board contain implicit walls).
	VWalls []*Position `protobuf:"bytes,2,rep,name=v_walls,json=vWalls,proto3" json:"v_walls,omitempty"`
	// Locations of the horizontal walls (edges of board contain implicit walls).
	HWalls        []*Position `protobuf:"bytes,3,rep,name=h_walls,json=hWalls,proto3" json:"h_walls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Board) Reset() {
	*x = Board{}
	mi := &file_bouncebot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Board) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Board) ProtoMessage() {}

func (x *Board) ProtoReflect() protoreflect.Message {
	mi := &file_bouncebot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Board.ProtoReflect.Descriptor instead.
func (*Board) Descriptor() ([]byte, []int) {
	return file_bouncebot_proto_rawDescGZIP(), []int{1}
}

func (x *Board) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Board) GetVWalls() []*Position {
	if x != nil {
		return x.VWalls
	}
	return nil
}

func (x *Board) GetHWalls() []*Position {
	if x != nil {
		return x.HWalls
	}
	return nil
}

type Bot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Pos           *Position              `protobuf:"bytes,2,opt,name=pos,proto3" json:"pos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bot) Reset() {
	*x = Bot{}
	mi := &file_bouncebot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bot) ProtoMessage() {}

func (x *Bot) ProtoReflect() protoreflect.Message {
	mi := &file_bouncebot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bot.ProtoReflect.Descriptor instead.
func (*Bot) Descriptor() ([]byte, []int) {
	return file_bouncebot_proto_rawDescGZIP(), []int{2}
}

func (x *Bot) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Bot) GetPos() *Position {
	if x != nil {
		return x.Pos
	}
	return nil
}

type GetBoardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          int32                  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBoardRequest) Reset() {
	*x = GetBoardRequest{}
	mi := &file_bouncebot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoardRequest) ProtoMessage() {}

func (x *GetBoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bouncebot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoardRequest.ProtoReflect.Descriptor instead.
func (*GetBoardRequest) Descriptor() ([]byte, []int) {
	return file_bouncebot_proto_rawDescGZIP(), []int{3}
}

func (x *GetBoardRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type GetBoardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Board         *Board                 `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`
	Bots          []*Bot                 `protobuf:"bytes,2,rep,name=bots,proto3" json:"bots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBoardResponse) Reset() {
	*x = GetBoardResponse{}
	mi := &file_bouncebot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBoardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoardResponse) ProtoMessage() {}

func (x *GetBoardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bouncebot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoardResponse.ProtoReflect.Descriptor instead.
func (*GetBoardResponse) Descriptor() ([]byte, []int) {
	return file_bouncebot_proto_rawDescGZIP(), []int{4}
}

func (x *GetBoardResponse) GetBoard() *Board {
	if x != nil {
		return x.Board
	}
	return nil
}

func (x *GetBoardResponse) GetBots() []*Bot {
	if x != nil {
		return x.Bots
	}
	return nil
}

var File_bouncebot_proto protoreflect.FileDescriptor

const file_bouncebot_proto_rawDesc = "" +
	"\n" +
	"\x0fbouncebot.proto\x12\tbouncebot\"&\n" +
	"\bPosition\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"w\n" +
	"\x05Board\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x05R\x04size\x12,\n" +
	"\av_walls\x18\x02 \x03(\v2\x13.bouncebot.PositionR\x06vWalls\x12,\n" +
	"\ah_walls\x18\x03 \x03(\v2\x13.bouncebot.PositionR\x06hWalls\"<\n" +
	"\x03Bot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12%\n" +
	"\x03pos\x18\x02 \x01(\v2\x13.bouncebot.PositionR\x03pos\"%\n" +
	"\x0fGetBoardRequest\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x05R\x04size\"^\n" +
	"\x10GetBoardResponse\x12&\n" +
	"\x05board\x18\x01 \x01(\v2\x10.bouncebot.BoardR\x05board\x12\"\n" +
	"\x04bots\x18\x02 \x03(\v2\x0e.bouncebot.BotR\x04bots2R\n" +
	"\tBounceBot\x12E\n" +
	"\bGetBoard\x12\x1a.bouncebot.GetBoardRequest\x1a\x1b.bouncebot.GetBoardResponse\"\x00B,Z*github.org/srsalisbury/bouncebot/bouncebotb\x06proto3"

var (
	file_bouncebot_proto_rawDescOnce sync.Once
	file_bouncebot_proto_rawDescData []byte
)

func file_bouncebot_proto_rawDescGZIP() []byte {
	file_bouncebot_proto_rawDescOnce.Do(func() {
		file_bouncebot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bouncebot_proto_rawDesc), len(file_bouncebot_proto_rawDesc)))
	})
	return file_bouncebot_proto_rawDescData
}

var file_bouncebot_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_bouncebot_proto_goTypes = []any{
	(*Position)(nil),         // 0: bouncebot.Position
	(*Board)(nil),            // 1: bouncebot.Board
	(*Bot)(nil),              // 2: bouncebot.Bot
	(*GetBoardRequest)(nil),  // 3: bouncebot.GetBoardRequest
	(*GetBoardResponse)(nil), // 4: bouncebot.GetBoardResponse
}
var file_bouncebot_proto_depIdxs = []int32{
	0, // 0: bouncebot.Board.v_walls:type_name -> bouncebot.Position
	0, // 1: bouncebot.Board.h_walls:type_name -> bouncebot.Position
	0, // 2: bouncebot.Bot.pos:type_name -> bouncebot.Position
	1, // 3: bouncebot.GetBoardResponse.board:type_name -> bouncebot.Board
	2, // 4: bouncebot.GetBoardResponse.bots:type_name -> bouncebot.Bot
	3, // 5: bouncebot.BounceBot.GetBoard:input_type -> bouncebot.GetBoardRequest
	4, // 6: bouncebot.BounceBot.GetBoard:output_type -> bouncebot.GetBoardResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_bouncebot_proto_init() }
func file_bouncebot_proto_init() {
	if File_bouncebot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bouncebot_proto_rawDesc), len(file_bouncebot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bouncebot_proto_goTypes,
		DependencyIndexes: file_bouncebot_proto_depIdxs,
		MessageInfos:      file_bouncebot_proto_msgTypes,
	}.Build()
	File_bouncebot_proto = out.File
	file_bouncebot_proto_goTypes = nil
	file_bouncebot_proto_depIdxs = nil
}
