// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.4
// source: bouncebot.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BounceBot_CreateRoom_FullMethodName          = "/bouncebot.BounceBot/CreateRoom"
	BounceBot_JoinRoom_FullMethodName            = "/bouncebot.BounceBot/JoinRoom"
	BounceBot_GetRoom_FullMethodName             = "/bouncebot.BounceBot/GetRoom"
	BounceBot_StartGame_FullMethodName           = "/bouncebot.BounceBot/StartGame"
	BounceBot_SubmitSolution_FullMethodName      = "/bouncebot.BounceBot/SubmitSolution"
	BounceBot_MarkFinishedSolving_FullMethodName = "/bouncebot.BounceBot/MarkFinishedSolving"
	BounceBot_MarkReadyForNext_FullMethodName    = "/bouncebot.BounceBot/MarkReadyForNext"
	BounceBot_UpdateRoomSettings_FullMethodName  = "/bouncebot.BounceBot/UpdateRoomSettings"
	BounceBot_BootPlayer_FullMethodName          = "/bouncebot.BounceBot/BootPlayer"
	BounceBot_LeaveRoom_FullMethodName           = "/bouncebot.BounceBot/LeaveRoom"
	BounceBot_GetDailyChallenge_FullMethodName   = "/bouncebot.BounceBot/GetDailyChallenge"
	BounceBot_SubmitDailySolution_FullMethodName = "/bouncebot.BounceBot/SubmitDailySolution"
	BounceBot_GetServerInfo_FullMethodName       = "/bouncebot.BounceBot/GetServerInfo"
)

// BounceBotClient is the client API for BounceBot service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for client to fetch a game board and return results.
type BounceBotClient interface {
	// Room management
	CreateRoom(ctx context.Context, in *CreateRoomRequest, opts ...grpc.CallOption) (*CreateRoomResponse, error)
	JoinRoom(ctx context.Context, in *JoinRoomRequest, opts ...grpc.CallOption) (*JoinRoomResponse, error)
	GetRoom(ctx context.Context, in *GetRoomRequest, opts ...grpc.CallOption) (*Room, error)
	StartGame(ctx context.Context, in *StartGameRequest, opts ...grpc.CallOption) (*Room, error)
	SubmitSolution(ctx context.Context, in *SubmitSolutionRequest, opts ...grpc.CallOption) (*SubmitSolutionResponse, error)
	MarkFinishedSolving(ctx context.Context, in *MarkFinishedSolvingRequest, opts ...grpc.CallOption) (*MarkFinishedSolvingResponse, error)
	MarkReadyForNext(ctx context.Context, in *MarkReadyForNextRequest, opts ...grpc.CallOption) (*MarkReadyForNextResponse, error)
	UpdateRoomSettings(ctx context.Context, in *UpdateRoomSettingsRequest, opts ...grpc.CallOption) (*UpdateRoomSettingsResponse, error)
	BootPlayer(ctx context.Context, in *BootPlayerRequest, opts ...grpc.CallOption) (*BootPlayerResponse, error)
	LeaveRoom(ctx context.Context, in *LeaveRoomRequest, opts ...grpc.CallOption) (*LeaveRoomResponse, error)
	// Daily challenge
	GetDailyChallenge(ctx context.Context, in *GetDailyChallengeRequest, opts ...grpc.CallOption) (*GetDailyChallengeResponse, error)
	SubmitDailySolution(ctx context.Context, in *SubmitDailySolutionRequest, opts ...grpc.CallOption) (*SubmitDailySolutionResponse, error)
	// Server info
	GetServerInfo(ctx context.Context, in *GetServerInfoRequest, opts ...grpc.CallOption) (*GetServerInfoResponse, error)
}

type bounceBotClient struct {
	cc grpc.ClientConnInterface
}

func NewBounceBotClient(cc grpc.ClientConnInterface) BounceBotClient {
	return &bounceBotClient{cc}
}

func (c *bounceBotClient) CreateRoom(ctx context.Context, in *CreateRoomRequest, opts ...grpc.CallOption) (*CreateRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRoomResponse)
	err := c.cc.Invoke(ctx, BounceBot_CreateRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bounceBotClient) JoinRoom(ctx context.Context, in *JoinRoomRequest, opts ...grpc.CallOption) (*JoinRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinRoomResponse)
	err := c.cc.Invoke(ctx, BounceBot_JoinRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bounceBotClient) GetRoom(ctx context.Context, in *GetRoomRequest, opts ...grpc.CallOption) (*Room, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Room)
	err := c.cc.Invoke(ctx, BounceBot_GetRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bounceBotClient) StartGame(ctx context.Context, in *StartGameRequest, opts ...grpc.CallOption) (*Room, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Room)
	err := c.cc.Invoke(ctx, BounceBot_StartGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bounceBotClient) SubmitSolution(ctx context.Context, in *SubmitSolutionRequest, opts ...grpc.CallOption) (*SubmitSolutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitSolutionResponse)
	err := c.cc.Invoke(ctx, BounceBot_SubmitSolution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bounceBotClient) MarkFinishedSolving(ctx context.Context, in *MarkFinishedSolvingRequest, opts ...grpc.CallOption) (*MarkFinishedSolvingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkFinishedSolvingResponse)
	err := c.cc.Invoke(ctx, BounceBot_MarkFinishedSolving_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bounceBotClient) MarkReadyForNext(ctx context.Context, in *MarkReadyForNextRequest, opts ...grpc.CallOption) (*MarkReadyForNextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkReadyForNextResponse)
	err := c.cc.Invoke(ctx, BounceBot_MarkReadyForNext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bounceBotClient) UpdateRoomSettings(ctx context.Context, in *UpdateRoomSettingsRequest, opts ...grpc.CallOption) (*UpdateRoomSettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRoomSettingsResponse)
	err := c.cc.Invoke(ctx, BounceBot_UpdateRoomSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bounceBotClient) BootPlayer(ctx context.Context, in *BootPlayerRequest, opts ...grpc.CallOption) (*BootPlayerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BootPlayerResponse)
	err := c.cc.Invoke(ctx, BounceBot_BootPlayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bounceBotClient) LeaveRoom(ctx context.Context, in *LeaveRoomRequest, opts ...grpc.CallOption) (*LeaveRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaveRoomResponse)
	err := c.cc.Invoke(ctx, BounceBot_LeaveRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bounceBotClient) GetDailyChallenge(ctx context.Context, in *GetDailyChallengeRequest, opts ...grpc.CallOption) (*GetDailyChallengeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDailyChallengeResponse)
	err := c.cc.Invoke(ctx, BounceBot_GetDailyChallenge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bounceBotClient) SubmitDailySolution(ctx context.Context, in *SubmitDailySolutionRequest, opts ...grpc.CallOption) (*SubmitDailySolutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitDailySolutionResponse)
	err := c.cc.Invoke(ctx, BounceBot_SubmitDailySolution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bounceBotClient) GetServerInfo(ctx context.Context, in *GetServerInfoRequest, opts ...grpc.CallOption) (*GetServerInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServerInfoResponse)
	err := c.cc.Invoke(ctx, BounceBot_GetServerInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BounceBotServer is the server API for BounceBot service.
// All implementations must embed UnimplementedBounceBotServer
// for forward compatibility.
//
// Service for client to fetch a game board and return results.
type BounceBotServer interface {
	// Room management
	CreateRoom(context.Context, *CreateRoomRequest) (*CreateRoomResponse, error)
	JoinRoom(context.Context, *JoinRoomRequest) (*JoinRoomResponse, error)
	GetRoom(context.Context, *GetRoomRequest) (*Room, error)
	StartGame(context.Context, *StartGameRequest) (*Room, error)
	SubmitSolution(context.Context, *SubmitSolutionRequest) (*SubmitSolutionResponse, error)
	MarkFinishedSolving(context.Context, *MarkFinishedSolvingRequest) (*MarkFinishedSolvingResponse, error)
	MarkReadyForNext(context.Context, *MarkReadyForNextRequest) (*MarkReadyForNextResponse, error)
	UpdateRoomSettings(context.Context, *UpdateRoomSettingsRequest) (*UpdateRoomSettingsResponse, error)
	BootPlayer(context.Context, *BootPlayerRequest) (*BootPlayerResponse, error)
	LeaveRoom(context.Context, *LeaveRoomRequest) (*LeaveRoomResponse, error)
	// Daily challenge
	GetDailyChallenge(context.Context, *GetDailyChallengeRequest) (*GetDailyChallengeResponse, error)
	SubmitDailySolution(context.Context, *SubmitDailySolutionRequest) (*SubmitDailySolutionResponse, error)
	// Server info
	GetServerInfo(context.Context, *GetServerInfoRequest) (*GetServerInfoResponse, error)
	mustEmbedUnimplementedBounceBotServer()
}

// UnimplementedBounceBotServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBounceBotServer struct{}

func (UnimplementedBounceBotServer) CreateRoom(context.Context, *CreateRoomRequest) (*CreateRoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRoom not implemented")
}
func (UnimplementedBounceBotServer) JoinRoom(context.Context, *JoinRoomRequest) (*JoinRoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinRoom not implemented")
}
func (UnimplementedBounceBotServer) GetRoom(context.Context, *GetRoomRequest) (*Room, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRoom not implemented")
}
func (UnimplementedBounceBotServer) StartGame(context.Context, *StartGameRequest) (*Room, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartGame not implemented")
}
func (UnimplementedBounceBotServer) SubmitSolution(context.Context, *SubmitSolutionRequest) (*SubmitSolutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitSolution not implemented")
}
func (UnimplementedBounceBotServer) MarkFinishedSolving(context.Context, *MarkFinishedSolvingRequest) (*MarkFinishedSolvingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkFinishedSolving not implemented")
}
func (UnimplementedBounceBotServer) MarkReadyForNext(context.Context, *MarkReadyForNextRequest) (*MarkReadyForNextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkReadyForNext not implemented")
}
func (UnimplementedBounceBotServer) UpdateRoomSettings(context.Context, *UpdateRoomSettingsRequest) (*UpdateRoomSettingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRoomSettings not implemented")
}
func (UnimplementedBounceBotServer) BootPlayer(context.Context, *BootPlayerRequest) (*BootPlayerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BootPlayer not implemented")
}
func (UnimplementedBounceBotServer) LeaveRoom(context.Context, *LeaveRoomRequest) (*LeaveRoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LeaveRoom not implemented")
}
func (UnimplementedBounceBotServer) GetDailyChallenge(context.Context, *GetDailyChallengeRequest) (*GetDailyChallengeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDailyChallenge not implemented")
}
func (UnimplementedBounceBotServer) SubmitDailySolution(context.Context, *SubmitDailySolutionRequest) (*SubmitDailySolutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitDailySolution not implemented")
}
func (UnimplementedBounceBotServer) GetServerInfo(context.Context, *GetServerInfoRequest) (*GetServerInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServerInfo not implemented")
}
func (UnimplementedBounceBotServer) mustEmbedUnimplementedBounceBotServer() {}
func (UnimplementedBounceBotServer) testEmbeddedByValue()                   {}

// UnsafeBounceBotServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BounceBotServer will
// result in compilation errors.
type UnsafeBounceBotServer interface {
	mustEmbedUnimplementedBounceBotServer()
}

func RegisterBounceBotServer(s grpc.ServiceRegistrar, srv BounceBotServer) {
	// If the following call pancis, it indicates UnimplementedBounceBotServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BounceBot_ServiceDesc, srv)
}

func _BounceBot_CreateRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BounceBotServer).CreateRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BounceBot_CreateRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BounceBotServer).CreateRoom(ctx, req.(*CreateRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BounceBot_JoinRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BounceBotServer).JoinRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BounceBot_JoinRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BounceBotServer).JoinRoom(ctx, req.(*JoinRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BounceBot_GetRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BounceBotServer).GetRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BounceBot_GetRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BounceBotServer).GetRoom(ctx, req.(*GetRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BounceBot_StartGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BounceBotServer).StartGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BounceBot_StartGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BounceBotServer).StartGame(ctx, req.(*StartGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BounceBot_SubmitSolution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitSolutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BounceBotServer).SubmitSolution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BounceBot_SubmitSolution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BounceBotServer).SubmitSolution(ctx, req.(*SubmitSolutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BounceBot_MarkFinishedSolving_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkFinishedSolvingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BounceBotServer).MarkFinishedSolving(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BounceBot_MarkFinishedSolving_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BounceBotServer).MarkFinishedSolving(ctx, req.(*MarkFinishedSolvingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BounceBot_MarkReadyForNext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkReadyForNextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BounceBotServer).MarkReadyForNext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BounceBot_MarkReadyForNext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BounceBotServer).MarkReadyForNext(ctx, req.(*MarkReadyForNextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BounceBot_UpdateRoomSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRoomSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BounceBotServer).UpdateRoomSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BounceBot_UpdateRoomSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BounceBotServer).UpdateRoomSettings(ctx, req.(*UpdateRoomSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BounceBot_BootPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BootPlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BounceBotServer).BootPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BounceBot_BootPlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BounceBotServer).BootPlayer(ctx, req.(*BootPlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BounceBot_LeaveRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BounceBotServer).LeaveRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BounceBot_LeaveRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BounceBotServer).LeaveRoom(ctx, req.(*LeaveRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BounceBot_GetDailyChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDailyChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BounceBotServer).GetDailyChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BounceBot_GetDailyChallenge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BounceBotServer).GetDailyChallenge(ctx, req.(*GetDailyChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BounceBot_SubmitDailySolution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitDailySolutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BounceBotServer).SubmitDailySolution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BounceBot_SubmitDailySolution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BounceBotServer).SubmitDailySolution(ctx, req.(*SubmitDailySolutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BounceBot_GetServerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServerInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BounceBotServer).GetServerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BounceBot_GetServerInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BounceBotServer).GetServerInfo(ctx, req.(*GetServerInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BounceBot_ServiceDesc is the grpc.ServiceDesc for BounceBot service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BounceBot_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bouncebot.BounceBot",
	HandlerType: (*BounceBotServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRoom",
			Handler:    _BounceBot_CreateRoom_Handler,
		},
		{
			MethodName: "JoinRoom",
			Handler:    _BounceBot_JoinRoom_Handler,
		},
		{
			MethodName: "GetRoom",
			Handler:    _BounceBot_GetRoom_Handler,
		},
		{
			MethodName: "StartGame",
			Handler:    _BounceBot_StartGame_Handler,
		},
		{
			MethodName: "SubmitSolution",
			Handler:    _BounceBot_SubmitSolution_Handler,
		},
		{
			MethodName: "MarkFinishedSolving",
			Handler:    _BounceBot_MarkFinishedSolving_Handler,
		},
		{
			MethodName: "MarkReadyForNext",
			Handler:    _BounceBot_MarkReadyForNext_Handler,
		},
		{
			MethodName: "UpdateRoomSettings",
			Handler:    _BounceBot_UpdateRoomSettings_Handler,
		},
		{
			MethodName: "BootPlayer",
			Handler:    _BounceBot_BootPlayer_Handler,
		},
		{
			MethodName: "LeaveRoom",
			Handler:    _BounceBot_LeaveRoom_Handler,
		},
		{
			MethodName: "GetDailyChallenge",
			Handler:    _BounceBot_GetDailyChallenge_Handler,
		},
		{
			MethodName: "SubmitDailySolution",
			Handler:    _BounceBot_SubmitDailySolution_Handler,
		},
		{
			MethodName: "GetServerInfo",
			Handler:    _BounceBot_GetServerInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bouncebot.proto",
}
