// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: bouncebot.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Board grid position.
// This refers to a board position relative to the upper-left board cell.
// For robots, this is the cell the robot sits on.
// For vertical walls, this is the cell to the left of the wall (the wall is to the right).
// For horizontal walls, this is the cell above the wall (the wall below the cell).
type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_bouncebot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_bouncebot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_bouncebot_proto_rawDescGZIP(), []int{0}
}

func (x *Position) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Board struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Board is square with size cells horizontally and vertically.
	Size int32 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	// Locations of the vertical walls (edges of board contain implicit walls).
	VWalls []*Position `protobuf:"bytes,2,rep,name=v_walls,json=vWalls,proto3" json:"v_walls,omitempty"`
	// Locations of the horizontal walls (edges of board contain implicit walls).
	HWalls        []*Position `protobuf:"bytes,3,rep,name=h_walls,json=hWalls,proto3" json:"h_walls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Board) Reset() {
	*x = Board{}
	mi := &file_bouncebot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Board) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Board) ProtoMessage() {}

func (x *Board) ProtoReflect() protoreflect.Message {
	mi := &file_bouncebot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Board.ProtoReflect.Descriptor instead.
func (*Board) Descriptor() ([]byte, []int) {
	return file_bouncebot_proto_rawDescGZIP(), []int{1}
}

func (x *Board) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Board) GetVWalls() []*Position {
	if x != nil {
		return x.VWalls
	}
	return nil
}

func (x *Board) GetHWalls() []*Position {
	if x != nil {
		return x.HWalls
	}
	return nil
}

type BotPos struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Pos           *Position              `protobuf:"bytes,2,opt,name=pos,proto3" json:"pos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotPos) Reset() {
	*x = BotPos{}
	mi := &file_bouncebot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotPos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotPos) ProtoMessage() {}

func (x *BotPos) ProtoReflect() protoreflect.Message {
	mi := &file_bouncebot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotPos.ProtoReflect.Descriptor instead.
func (*BotPos) Descriptor() ([]byte, []int) {
	return file_bouncebot_proto_rawDescGZIP(), []int{2}
}

func (x *BotPos) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BotPos) GetPos() *Position {
	if x != nil {
		return x.Pos
	}
	return nil
}

type Game struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Board         *Board                 `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`
	Bots          []*BotPos              `protobuf:"bytes,2,rep,name=bots,proto3" json:"bots,omitempty"`
	Target        *BotPos                `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Game) Reset() {
	*x = Game{}
	mi := &file_bouncebot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game) ProtoMessage() {}

func (x *Game) ProtoReflect() protoreflect.Message {
	mi := &file_bouncebot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game.ProtoReflect.Descriptor instead.
func (*Game) Descriptor() ([]byte, []int) {
	return file_bouncebot_proto_rawDescGZIP(), []int{3}
}

func (x *Game) GetBoard() *Board {
	if x != nil {
		return x.Board
	}
	return nil
}

func (x *Game) GetBots() []*BotPos {
	if x != nil {
		return x.Bots
	}
	return nil
}

func (x *Game) GetTarget() *BotPos {
	if x != nil {
		return x.Target
	}
	return nil
}

type MakeGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          int32                  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeGameRequest) Reset() {
	*x = MakeGameRequest{}
	mi := &file_bouncebot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeGameRequest) ProtoMessage() {}

func (x *MakeGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bouncebot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeGameRequest.ProtoReflect.Descriptor instead.
func (*MakeGameRequest) Descriptor() ([]byte, []int) {
	return file_bouncebot_proto_rawDescGZIP(), []int{4}
}

func (x *MakeGameRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type CheckSolutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game          *Game                  `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	Moves         []*BotPos              `protobuf:"bytes,2,rep,name=moves,proto3" json:"moves,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckSolutionRequest) Reset() {
	*x = CheckSolutionRequest{}
	mi := &file_bouncebot_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckSolutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSolutionRequest) ProtoMessage() {}

func (x *CheckSolutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bouncebot_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSolutionRequest.ProtoReflect.Descriptor instead.
func (*CheckSolutionRequest) Descriptor() ([]byte, []int) {
	return file_bouncebot_proto_rawDescGZIP(), []int{5}
}

func (x *CheckSolutionRequest) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

func (x *CheckSolutionRequest) GetMoves() []*BotPos {
	if x != nil {
		return x.Moves
	}
	return nil
}

type CheckSolutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	NumMoves      int32                  `protobuf:"varint,2,opt,name=num_moves,json=numMoves,proto3" json:"num_moves,omitempty"`
	ResultingGame *Game                  `protobuf:"bytes,3,opt,name=resulting_game,json=resultingGame,proto3" json:"resulting_game,omitempty"`
	FirstBadMove  *MoveError             `protobuf:"bytes,4,opt,name=first_bad_move,json=firstBadMove,proto3" json:"first_bad_move,omitempty"` // If solution is not valid
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckSolutionResponse) Reset() {
	*x = CheckSolutionResponse{}
	mi := &file_bouncebot_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckSolutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSolutionResponse) ProtoMessage() {}

func (x *CheckSolutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bouncebot_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSolutionResponse.ProtoReflect.Descriptor instead.
func (*CheckSolutionResponse) Descriptor() ([]byte, []int) {
	return file_bouncebot_proto_rawDescGZIP(), []int{6}
}

func (x *CheckSolutionResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *CheckSolutionResponse) GetNumMoves() int32 {
	if x != nil {
		return x.NumMoves
	}
	return 0
}

func (x *CheckSolutionResponse) GetResultingGame() *Game {
	if x != nil {
		return x.ResultingGame
	}
	return nil
}

func (x *CheckSolutionResponse) GetFirstBadMove() *MoveError {
	if x != nil {
		return x.FirstBadMove
	}
	return nil
}

type MoveError struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Move             *BotPos                `protobuf:"bytes,1,opt,name=move,proto3" json:"move,omitempty"`
	ErrorDescription string                 `protobuf:"bytes,2,opt,name=error_description,json=errorDescription,proto3" json:"error_description,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MoveError) Reset() {
	*x = MoveError{}
	mi := &file_bouncebot_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveError) ProtoMessage() {}

func (x *MoveError) ProtoReflect() protoreflect.Message {
	mi := &file_bouncebot_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveError.ProtoReflect.Descriptor instead.
func (*MoveError) Descriptor() ([]byte, []int) {
	return file_bouncebot_proto_rawDescGZIP(), []int{7}
}

func (x *MoveError) GetMove() *BotPos {
	if x != nil {
		return x.Move
	}
	return nil
}

func (x *MoveError) GetErrorDescription() string {
	if x != nil {
		return x.ErrorDescription
	}
	return ""
}

// Player in a room
type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_bouncebot_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_bouncebot_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_bouncebot_proto_rawDescGZIP(), []int{8}
}

func (x *Player) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Player's solution result
type PlayerSolution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	SolvedAt      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=solved_at,json=solvedAt,proto3" json:"solved_at,omitempty"`
	Moves         []*BotPos              `protobuf:"bytes,3,rep,name=moves,proto3" json:"moves,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerSolution) Reset() {
	*x = PlayerSolution{}
	mi := &file_bouncebot_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerSolution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerSolution) ProtoMessage() {}

func (x *PlayerSolution) ProtoReflect() protoreflect.Message {
	mi := &file_bouncebot_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerSolution.ProtoReflect.Descriptor instead.
func (*PlayerSolution) Descriptor() ([]byte, []int) {
	return file_bouncebot_proto_rawDescGZIP(), []int{9}
}

func (x *PlayerSolution) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerSolution) GetSolvedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SolvedAt
	}
	return nil
}

func (x *PlayerSolution) GetMoves() []*BotPos {
	if x != nil {
		return x.Moves
	}
	return nil
}

// Player's cumulative score in the room
type PlayerScore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Wins          int32                  `protobuf:"varint,2,opt,name=wins,proto3" json:"wins,omitempty"` // number of games won
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerScore) Reset() {
	*x = PlayerScore{}
	mi := &file_bouncebot_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerScore) ProtoMessage() {}

func (x *PlayerScore) ProtoReflect() protoreflect.Message {
	mi := &file_bouncebot_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerScore.ProtoReflect.Descriptor instead.
func (*PlayerScore) Descriptor() ([]byte, []int) {
	return file_bouncebot_proto_rawDescGZIP(), []int{10}
}

func (x *PlayerScore) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerScore) GetWins() int32 {
	if x != nil {
		return x.Wins
	}
	return 0
}

// Game room for multiplayer
type Room struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Players         []*Player              `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CurrentGame     *Game                  `protobuf:"bytes,4,opt,name=current_game,json=currentGame,proto3" json:"current_game,omitempty"`             // null if no game started yet
	GameStartedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=game_started_at,json=gameStartedAt,proto3" json:"game_started_at,omitempty"`     // when current game started
	Solutions       []*PlayerSolution      `protobuf:"bytes,6,rep,name=solutions,proto3" json:"solutions,omitempty"`                                    // players who have solved the current game
	Scores          []*PlayerScore         `protobuf:"bytes,7,rep,name=scores,proto3" json:"scores,omitempty"`                                          // cumulative scores across games
	GamesPlayed     int32                  `protobuf:"varint,8,opt,name=games_played,json=gamesPlayed,proto3" json:"games_played,omitempty"`            // total games completed in room
	FinishedSolving []string               `protobuf:"bytes,9,rep,name=finished_solving,json=finishedSolving,proto3" json:"finished_solving,omitempty"` // player IDs who are finished solving (triggers game end)
	ReadyForNext    []string               `protobuf:"bytes,10,rep,name=ready_for_next,json=readyForNext,proto3" json:"ready_for_next,omitempty"`       // player IDs who are ready for next game
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Room) Reset() {
	*x = Room{}
	mi := &file_bouncebot_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_bouncebot_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_bouncebot_proto_rawDescGZIP(), []int{11}
}

func (x *Room) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Room) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *Room) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Room) GetCurrentGame() *Game {
	if x != nil {
		return x.CurrentGame
	}
	return nil
}

func (x *Room) GetGameStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GameStartedAt
	}
	return nil
}

func (x *Room) GetSolutions() []*PlayerSolution {
	if x != nil {
		return x.Solutions
	}
	return nil
}

func (x *Room) GetScores() []*PlayerScore {
	if x != nil {
		return x.Scores
	}
	return nil
}

func (x *Room) GetGamesPlayed() int32 {
	if x != nil {
		return x.GamesPlayed
	}
	return 0
}

func (x *Room) GetFinishedSolving() []string {
	if x != nil {
		return x.FinishedSolving
	}
	return nil
}

func (x *Room) GetReadyForNext() []string {
	if x != nil {
		return x.ReadyForNext
	}
	return nil
}

type CreateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerName    string                 `protobuf:"bytes,1,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	mi := &file_bouncebot_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bouncebot_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_bouncebot_proto_rawDescGZIP(), []int{12}
}

func (x *CreateRoomRequest) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

type JoinRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	PlayerName    string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomRequest) Reset() {
	*x = JoinRoomRequest{}
	mi := &file_bouncebot_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomRequest) ProtoMessage() {}

func (x *JoinRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bouncebot_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomRequest.ProtoReflect.Descriptor instead.
func (*JoinRoomRequest) Descriptor() ([]byte, []int) {
	return file_bouncebot_proto_rawDescGZIP(), []int{13}
}

func (x *JoinRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *JoinRoomRequest) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

type GetRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomRequest) Reset() {
	*x = GetRoomRequest{}
	mi := &file_bouncebot_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomRequest) ProtoMessage() {}

func (x *GetRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bouncebot_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomRequest.ProtoReflect.Descriptor instead.
func (*GetRoomRequest) Descriptor() ([]byte, []int) {
	return file_bouncebot_proto_rawDescGZIP(), []int{14}
}

func (x *GetRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type StartGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UseFixedBoard bool                   `protobuf:"varint,2,opt,name=use_fixed_board,json=useFixedBoard,proto3" json:"use_fixed_board,omitempty"` // If true, use Game1() instead of random
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartGameRequest) Reset() {
	*x = StartGameRequest{}
	mi := &file_bouncebot_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGameRequest) ProtoMessage() {}

func (x *StartGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bouncebot_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGameRequest.ProtoReflect.Descriptor instead.
func (*StartGameRequest) Descriptor() ([]byte, []int) {
	return file_bouncebot_proto_rawDescGZIP(), []int{15}
}

func (x *StartGameRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *StartGameRequest) GetUseFixedBoard() bool {
	if x != nil {
		return x.UseFixedBoard
	}
	return false
}

type SubmitSolutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Moves         []*BotPos              `protobuf:"bytes,3,rep,name=moves,proto3" json:"moves,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitSolutionRequest) Reset() {
	*x = SubmitSolutionRequest{}
	mi := &file_bouncebot_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitSolutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitSolutionRequest) ProtoMessage() {}

func (x *SubmitSolutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bouncebot_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitSolutionRequest.ProtoReflect.Descriptor instead.
func (*SubmitSolutionRequest) Descriptor() ([]byte, []int) {
	return file_bouncebot_proto_rawDescGZIP(), []int{16}
}

func (x *SubmitSolutionRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SubmitSolutionRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *SubmitSolutionRequest) GetMoves() []*BotPos {
	if x != nil {
		return x.Moves
	}
	return nil
}

type SubmitSolutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Solution      *PlayerSolution        `protobuf:"bytes,1,opt,name=solution,proto3" json:"solution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitSolutionResponse) Reset() {
	*x = SubmitSolutionResponse{}
	mi := &file_bouncebot_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitSolutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitSolutionResponse) ProtoMessage() {}

func (x *SubmitSolutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bouncebot_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitSolutionResponse.ProtoReflect.Descriptor instead.
func (*SubmitSolutionResponse) Descriptor() ([]byte, []int) {
	return file_bouncebot_proto_rawDescGZIP(), []int{17}
}

func (x *SubmitSolutionResponse) GetSolution() *PlayerSolution {
	if x != nil {
		return x.Solution
	}
	return nil
}

type RetractSolutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetractSolutionRequest) Reset() {
	*x = RetractSolutionRequest{}
	mi := &file_bouncebot_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetractSolutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetractSolutionRequest) ProtoMessage() {}

func (x *RetractSolutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bouncebot_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetractSolutionRequest.ProtoReflect.Descriptor instead.
func (*RetractSolutionRequest) Descriptor() ([]byte, []int) {
	return file_bouncebot_proto_rawDescGZIP(), []int{18}
}

func (x *RetractSolutionRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RetractSolutionRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type RetractSolutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetractSolutionResponse) Reset() {
	*x = RetractSolutionResponse{}
	mi := &file_bouncebot_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetractSolutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetractSolutionResponse) ProtoMessage() {}

func (x *RetractSolutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bouncebot_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetractSolutionResponse.ProtoReflect.Descriptor instead.
func (*RetractSolutionResponse) Descriptor() ([]byte, []int) {
	return file_bouncebot_proto_rawDescGZIP(), []int{19}
}

func (x *RetractSolutionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type MarkFinishedSolvingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkFinishedSolvingRequest) Reset() {
	*x = MarkFinishedSolvingRequest{}
	mi := &file_bouncebot_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkFinishedSolvingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkFinishedSolvingRequest) ProtoMessage() {}

func (x *MarkFinishedSolvingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bouncebot_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkFinishedSolvingRequest.ProtoReflect.Descriptor instead.
func (*MarkFinishedSolvingRequest) Descriptor() ([]byte, []int) {
	return file_bouncebot_proto_rawDescGZIP(), []int{20}
}

func (x *MarkFinishedSolvingRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *MarkFinishedSolvingRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type MarkFinishedSolvingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkFinishedSolvingResponse) Reset() {
	*x = MarkFinishedSolvingResponse{}
	mi := &file_bouncebot_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkFinishedSolvingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkFinishedSolvingResponse) ProtoMessage() {}

func (x *MarkFinishedSolvingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bouncebot_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkFinishedSolvingResponse.ProtoReflect.Descriptor instead.
func (*MarkFinishedSolvingResponse) Descriptor() ([]byte, []int) {
	return file_bouncebot_proto_rawDescGZIP(), []int{21}
}

func (x *MarkFinishedSolvingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type MarkReadyForNextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkReadyForNextRequest) Reset() {
	*x = MarkReadyForNextRequest{}
	mi := &file_bouncebot_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReadyForNextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReadyForNextRequest) ProtoMessage() {}

func (x *MarkReadyForNextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bouncebot_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReadyForNextRequest.ProtoReflect.Descriptor instead.
func (*MarkReadyForNextRequest) Descriptor() ([]byte, []int) {
	return file_bouncebot_proto_rawDescGZIP(), []int{22}
}

func (x *MarkReadyForNextRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *MarkReadyForNextRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type MarkReadyForNextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkReadyForNextResponse) Reset() {
	*x = MarkReadyForNextResponse{}
	mi := &file_bouncebot_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReadyForNextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReadyForNextResponse) ProtoMessage() {}

func (x *MarkReadyForNextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bouncebot_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReadyForNextResponse.ProtoReflect.Descriptor instead.
func (*MarkReadyForNextResponse) Descriptor() ([]byte, []int) {
	return file_bouncebot_proto_rawDescGZIP(), []int{23}
}

func (x *MarkReadyForNextResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_bouncebot_proto protoreflect.FileDescriptor

const file_bouncebot_proto_rawDesc = "" +
	"\n" +
	"\x0fbouncebot.proto\x12\tbouncebot\x1a\x1fgoogle/protobuf/timestamp.proto\"&\n" +
	"\bPosition\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"w\n" +
	"\x05Board\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x05R\x04size\x12,\n" +
	"\av_walls\x18\x02 \x03(\v2\x13.bouncebot.PositionR\x06vWalls\x12,\n" +
	"\ah_walls\x18\x03 \x03(\v2\x13.bouncebot.PositionR\x06hWalls\"?\n" +
	"\x06BotPos\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12%\n" +
	"\x03pos\x18\x02 \x01(\v2\x13.bouncebot.PositionR\x03pos\"\x80\x01\n" +
	"\x04Game\x12&\n" +
	"\x05board\x18\x01 \x01(\v2\x10.bouncebot.BoardR\x05board\x12%\n" +
	"\x04bots\x18\x02 \x03(\v2\x11.bouncebot.BotPosR\x04bots\x12)\n" +
	"\x06target\x18\x03 \x01(\v2\x11.bouncebot.BotPosR\x06target\"%\n" +
	"\x0fMakeGameRequest\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x05R\x04size\"d\n" +
	"\x14CheckSolutionRequest\x12#\n" +
	"\x04game\x18\x01 \x01(\v2\x0f.bouncebot.GameR\x04game\x12'\n" +
	"\x05moves\x18\x02 \x03(\v2\x11.bouncebot.BotPosR\x05moves\"\xc3\x01\n" +
	"\x15CheckSolutionResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\x12\x1b\n" +
	"\tnum_moves\x18\x02 \x01(\x05R\bnumMoves\x126\n" +
	"\x0eresulting_game\x18\x03 \x01(\v2\x0f.bouncebot.GameR\rresultingGame\x12:\n" +
	"\x0efirst_bad_move\x18\x04 \x01(\v2\x14.bouncebot.MoveErrorR\ffirstBadMove\"_\n" +
	"\tMoveError\x12%\n" +
	"\x04move\x18\x01 \x01(\v2\x11.bouncebot.BotPosR\x04move\x12+\n" +
	"\x11error_description\x18\x02 \x01(\tR\x10errorDescription\",\n" +
	"\x06Player\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x8f\x01\n" +
	"\x0ePlayerSolution\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x127\n" +
	"\tsolved_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bsolvedAt\x12'\n" +
	"\x05moves\x18\x03 \x03(\v2\x11.bouncebot.BotPosR\x05moves\">\n" +
	"\vPlayerScore\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x12\n" +
	"\x04wins\x18\x02 \x01(\x05R\x04wins\"\xd3\x03\n" +
	"\x04Room\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\aplayers\x18\x02 \x03(\v2\x11.bouncebot.PlayerR\aplayers\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x122\n" +
	"\fcurrent_game\x18\x04 \x01(\v2\x0f.bouncebot.GameR\vcurrentGame\x12B\n" +
	"\x0fgame_started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\rgameStartedAt\x127\n" +
	"\tsolutions\x18\x06 \x03(\v2\x19.bouncebot.PlayerSolutionR\tsolutions\x12.\n" +
	"\x06scores\x18\a \x03(\v2\x16.bouncebot.PlayerScoreR\x06scores\x12!\n" +
	"\fgames_played\x18\b \x01(\x05R\vgamesPlayed\x12)\n" +
	"\x10finished_solving\x18\t \x03(\tR\x0ffinishedSolving\x12$\n" +
	"\x0eready_for_next\x18\n" +
	" \x03(\tR\freadyForNext\"4\n" +
	"\x11CreateRoomRequest\x12\x1f\n" +
	"\vplayer_name\x18\x01 \x01(\tR\n" +
	"playerName\"K\n" +
	"\x0fJoinRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\")\n" +
	"\x0eGetRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"S\n" +
	"\x10StartGameRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12&\n" +
	"\x0fuse_fixed_board\x18\x02 \x01(\bR\ruseFixedBoard\"v\n" +
	"\x15SubmitSolutionRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12'\n" +
	"\x05moves\x18\x03 \x03(\v2\x11.bouncebot.BotPosR\x05moves\"O\n" +
	"\x16SubmitSolutionResponse\x125\n" +
	"\bsolution\x18\x01 \x01(\v2\x19.bouncebot.PlayerSolutionR\bsolution\"N\n" +
	"\x16RetractSolutionRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\"3\n" +
	"\x17RetractSolutionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"R\n" +
	"\x1aMarkFinishedSolvingRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\"7\n" +
	"\x1bMarkFinishedSolvingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"O\n" +
	"\x17MarkReadyForNextRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\"4\n" +
	"\x18MarkReadyForNextResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x88\x06\n" +
	"\tBounceBot\x129\n" +
	"\bMakeGame\x12\x1a.bouncebot.MakeGameRequest\x1a\x0f.bouncebot.Game\"\x00\x12T\n" +
	"\rCheckSolution\x12\x1f.bouncebot.CheckSolutionRequest\x1a .bouncebot.CheckSolutionResponse\"\x00\x12=\n" +
	"\n" +
	"CreateRoom\x12\x1c.bouncebot.CreateRoomRequest\x1a\x0f.bouncebot.Room\"\x00\x129\n" +
	"\bJoinRoom\x12\x1a.bouncebot.JoinRoomRequest\x1a\x0f.bouncebot.Room\"\x00\x127\n" +
	"\aGetRoom\x12\x19.bouncebot.GetRoomRequest\x1a\x0f.bouncebot.Room\"\x00\x12;\n" +
	"\tStartGame\x12\x1b.bouncebot.StartGameRequest\x1a\x0f.bouncebot.Room\"\x00\x12W\n" +
	"\x0eSubmitSolution\x12 .bouncebot.SubmitSolutionRequest\x1a!.bouncebot.SubmitSolutionResponse\"\x00\x12Z\n" +
	"\x0fRetractSolution\x12!.bouncebot.RetractSolutionRequest\x1a\".bouncebot.RetractSolutionResponse\"\x00\x12f\n" +
	"\x13MarkFinishedSolving\x12%.bouncebot.MarkFinishedSolvingRequest\x1a&.bouncebot.MarkFinishedSolvingResponse\"\x00\x12]\n" +
	"\x10MarkReadyForNext\x12\".bouncebot.MarkReadyForNextRequest\x1a#.bouncebot.MarkReadyForNextResponse\"\x00B(Z&github.com/srsalisbury/bouncebot/protob\x06proto3"

var (
	file_bouncebot_proto_rawDescOnce sync.Once
	file_bouncebot_proto_rawDescData []byte
)

func file_bouncebot_proto_rawDescGZIP() []byte {
	file_bouncebot_proto_rawDescOnce.Do(func() {
		file_bouncebot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bouncebot_proto_rawDesc), len(file_bouncebot_proto_rawDesc)))
	})
	return file_bouncebot_proto_rawDescData
}

var file_bouncebot_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_bouncebot_proto_goTypes = []any{
	(*Position)(nil),                    // 0: bouncebot.Position
	(*Board)(nil),                       // 1: bouncebot.Board
	(*BotPos)(nil),                      // 2: bouncebot.BotPos
	(*Game)(nil),                        // 3: bouncebot.Game
	(*MakeGameRequest)(nil),             // 4: bouncebot.MakeGameRequest
	(*CheckSolutionRequest)(nil),        // 5: bouncebot.CheckSolutionRequest
	(*CheckSolutionResponse)(nil),       // 6: bouncebot.CheckSolutionResponse
	(*MoveError)(nil),                   // 7: bouncebot.MoveError
	(*Player)(nil),                      // 8: bouncebot.Player
	(*PlayerSolution)(nil),              // 9: bouncebot.PlayerSolution
	(*PlayerScore)(nil),                 // 10: bouncebot.PlayerScore
	(*Room)(nil),                        // 11: bouncebot.Room
	(*CreateRoomRequest)(nil),           // 12: bouncebot.CreateRoomRequest
	(*JoinRoomRequest)(nil),             // 13: bouncebot.JoinRoomRequest
	(*GetRoomRequest)(nil),              // 14: bouncebot.GetRoomRequest
	(*StartGameRequest)(nil),            // 15: bouncebot.StartGameRequest
	(*SubmitSolutionRequest)(nil),       // 16: bouncebot.SubmitSolutionRequest
	(*SubmitSolutionResponse)(nil),      // 17: bouncebot.SubmitSolutionResponse
	(*RetractSolutionRequest)(nil),      // 18: bouncebot.RetractSolutionRequest
	(*RetractSolutionResponse)(nil),     // 19: bouncebot.RetractSolutionResponse
	(*MarkFinishedSolvingRequest)(nil),  // 20: bouncebot.MarkFinishedSolvingRequest
	(*MarkFinishedSolvingResponse)(nil), // 21: bouncebot.MarkFinishedSolvingResponse
	(*MarkReadyForNextRequest)(nil),     // 22: bouncebot.MarkReadyForNextRequest
	(*MarkReadyForNextResponse)(nil),    // 23: bouncebot.MarkReadyForNextResponse
	(*timestamppb.Timestamp)(nil),       // 24: google.protobuf.Timestamp
}
var file_bouncebot_proto_depIdxs = []int32{
	0,  // 0: bouncebot.Board.v_walls:type_name -> bouncebot.Position
	0,  // 1: bouncebot.Board.h_walls:type_name -> bouncebot.Position
	0,  // 2: bouncebot.BotPos.pos:type_name -> bouncebot.Position
	1,  // 3: bouncebot.Game.board:type_name -> bouncebot.Board
	2,  // 4: bouncebot.Game.bots:type_name -> bouncebot.BotPos
	2,  // 5: bouncebot.Game.target:type_name -> bouncebot.BotPos
	3,  // 6: bouncebot.CheckSolutionRequest.game:type_name -> bouncebot.Game
	2,  // 7: bouncebot.CheckSolutionRequest.moves:type_name -> bouncebot.BotPos
	3,  // 8: bouncebot.CheckSolutionResponse.resulting_game:type_name -> bouncebot.Game
	7,  // 9: bouncebot.CheckSolutionResponse.first_bad_move:type_name -> bouncebot.MoveError
	2,  // 10: bouncebot.MoveError.move:type_name -> bouncebot.BotPos
	24, // 11: bouncebot.PlayerSolution.solved_at:type_name -> google.protobuf.Timestamp
	2,  // 12: bouncebot.PlayerSolution.moves:type_name -> bouncebot.BotPos
	8,  // 13: bouncebot.Room.players:type_name -> bouncebot.Player
	24, // 14: bouncebot.Room.created_at:type_name -> google.protobuf.Timestamp
	3,  // 15: bouncebot.Room.current_game:type_name -> bouncebot.Game
	24, // 16: bouncebot.Room.game_started_at:type_name -> google.protobuf.Timestamp
	9,  // 17: bouncebot.Room.solutions:type_name -> bouncebot.PlayerSolution
	10, // 18: bouncebot.Room.scores:type_name -> bouncebot.PlayerScore
	2,  // 19: bouncebot.SubmitSolutionRequest.moves:type_name -> bouncebot.BotPos
	9,  // 20: bouncebot.SubmitSolutionResponse.solution:type_name -> bouncebot.PlayerSolution
	4,  // 21: bouncebot.BounceBot.MakeGame:input_type -> bouncebot.MakeGameRequest
	5,  // 22: bouncebot.BounceBot.CheckSolution:input_type -> bouncebot.CheckSolutionRequest
	12, // 23: bouncebot.BounceBot.CreateRoom:input_type -> bouncebot.CreateRoomRequest
	13, // 24: bouncebot.BounceBot.JoinRoom:input_type -> bouncebot.JoinRoomRequest
	14, // 25: bouncebot.BounceBot.GetRoom:input_type -> bouncebot.GetRoomRequest
	15, // 26: bouncebot.BounceBot.StartGame:input_type -> bouncebot.StartGameRequest
	16, // 27: bouncebot.BounceBot.SubmitSolution:input_type -> bouncebot.SubmitSolutionRequest
	18, // 28: bouncebot.BounceBot.RetractSolution:input_type -> bouncebot.RetractSolutionRequest
	20, // 29: bouncebot.BounceBot.MarkFinishedSolving:input_type -> bouncebot.MarkFinishedSolvingRequest
	22, // 30: bouncebot.BounceBot.MarkReadyForNext:input_type -> bouncebot.MarkReadyForNextRequest
	3,  // 31: bouncebot.BounceBot.MakeGame:output_type -> bouncebot.Game
	6,  // 32: bouncebot.BounceBot.CheckSolution:output_type -> bouncebot.CheckSolutionResponse
	11, // 33: bouncebot.BounceBot.CreateRoom:output_type -> bouncebot.Room
	11, // 34: bouncebot.BounceBot.JoinRoom:output_type -> bouncebot.Room
	11, // 35: bouncebot.BounceBot.GetRoom:output_type -> bouncebot.Room
	11, // 36: bouncebot.BounceBot.StartGame:output_type -> bouncebot.Room
	17, // 37: bouncebot.BounceBot.SubmitSolution:output_type -> bouncebot.SubmitSolutionResponse
	19, // 38: bouncebot.BounceBot.RetractSolution:output_type -> bouncebot.RetractSolutionResponse
	21, // 39: bouncebot.BounceBot.MarkFinishedSolving:output_type -> bouncebot.MarkFinishedSolvingResponse
	23, // 40: bouncebot.BounceBot.MarkReadyForNext:output_type -> bouncebot.MarkReadyForNextResponse
	31, // [31:41] is the sub-list for method output_type
	21, // [21:31] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_bouncebot_proto_init() }
func file_bouncebot_proto_init() {
	if File_bouncebot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bouncebot_proto_rawDesc), len(file_bouncebot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bouncebot_proto_goTypes,
		DependencyIndexes: file_bouncebot_proto_depIdxs,
		MessageInfos:      file_bouncebot_proto_msgTypes,
	}.Build()
	File_bouncebot_proto = out.File
	file_bouncebot_proto_goTypes = nil
	file_bouncebot_proto_depIdxs = nil
}
